### ISSUE TITLE
Artist Songs Crash

### ISSUE THREAD

**Issue by cd-FileX** [maxrave-dev/SimpMusic#117]
**Describe the bug**
Crash on trying to play "all songs" of an artist.

**To Reproduce**
0. Have a song playing in the search mix (in my case sasanqua) (and go from there to the artists page)
2. Go to an artists page (in my case SEKAI NO OWARI)
3. Click on "Show all" of the "Popular" part
4. Click on play
5. See error

**Expected behavior**
Obv.

**Screenshots**

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.

Also it would be good to add a <details> element to the crash log when copying, I think.

Build version: 0.1.3-beta 
Current date: 2023-10-11 19:40:18 
Device: DOOGEE S88Plus 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner for NowPlayingFragment{a85daef} (d7d3c811-0185-466c-be66-733e1e3b454f id=0x7f0a0193 tag=f0fecbbe-b483-4e0d-821f-ba1b1e32afa7) when getView() is null i.e., before onCreateView() or after onDestroyView()
	at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:385)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment.updateUIfromCurrentMediaItem(NowPlayingFragment.kt:1349)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment.access$updateUIfromCurrentMediaItem(NowPlayingFragment.kt:80)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment$onViewCreated$6$1$job7$1$1.invokeSuspend(NowPlayingFragment.kt:522)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment$onViewCreated$6$1$job7$1$1.invoke(Unknown Source:8)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment$onViewCreated$6$1$job7$1$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:217)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:8)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
	at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:235)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at kotlinx.coroutines.flow.StateFlowSlot.makePending(StateFlow.kt:284)
	at kotlinx.coroutines.flow.StateFlowImpl.updateState(StateFlow.kt:349)
	at kotlinx.coroutines.flow.StateFlowImpl.setValue(StateFlow.kt:316)
	at com.maxrave.simpmusic.service.SimpleMediaServiceHandler.onMediaItemTransition(SimpleMediaServiceHandler.kt:314)
	at androidx.media3.exoplayer.ExoPlayerImpl.lambda$updatePlaybackInfo$14(ExoPlayerImpl.java:2046)
	at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda27.invoke(Unknown Source:6)
	at androidx.media3.common.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:339)
	at androidx.media3.common.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:223)
	at androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at androidx.media3.common.util.ListenerSet.flushEvents(ListenerSet.java:245)
	at androidx.media3.exoplayer.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:2116)
	at androidx.media3.exoplayer.ExoPlayerImpl.setMediaSourcesInternal(ExoPlayerImpl.java:2332)
	at androidx.media3.exoplayer.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:611)
	at androidx.media3.exoplayer.ExoPlayerImpl.setMediaItems(ExoPlayerImpl.java:574)
	at androidx.media3.common.BasePlayer.setMediaItems(BasePlayer.java:56)
	at androidx.media3.common.BasePlayer.setMediaItem(BasePlayer.java:41)
	at com.maxrave.simpmusic.service.SimpleMediaServiceHandler.addMediaItem(SimpleMediaServiceHandler.kt:172)
	at com.maxrave.simpmusic.viewModel.SharedViewModel$loadMediaItemFromTrack$2$2.emit(SharedViewModel.kt:549)
	at com.maxrave.simpmusic.viewModel.SharedViewModel$loadMediaItemFromTrack$2$2.emit(SharedViewModel.kt:538)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a4e497f, Dispatchers.Main.immediate]

User actions: 
2023-10-11 19:27:46: MainActivity created
2023-10-11 19:27:46: MainActivity resumed
2023-10-11 19:29:20: MainActivity paused
2023-10-11 19:37:19: MainActivity resumed
2023-10-11 19:37:26: MainActivity paused
2023-10-11 19:39:24: MainActivity resumed

**Comment by maxrave-dev** [comment]
Trying new version v0.1.4
