### ISSUE TITLE
App crash while downloading music/some other music player is playing music.

### ISSUE THREAD

**Issue by aayushrautela** [maxrave-dev/SimpMusic#119]
Build version: 0.1.4-beta 
Current date: 2023-10-11 16:31:41 
Device: Google Pixel 6 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{1ad4335 24348:com.maxrave.simpmusic/u0a590} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
	at android.app.Service.startForeground(Service.java:775)
	at androidx.media3.exoplayer.offline.DownloadService$ForegroundNotificationUpdater.update(DownloadService.java:920)
	at androidx.media3.exoplayer.offline.DownloadService$ForegroundNotificationUpdater.startPeriodicUpdates(DownloadService.java:893)
	at androidx.media3.exoplayer.offline.DownloadService.notifyDownloadChanged(DownloadService.java:810)
	at androidx.media3.exoplayer.offline.DownloadService.access$400(DownloadService.java:54)
	at androidx.media3.exoplayer.offline.DownloadService$DownloadManagerHelper.onDownloadChanged(DownloadService.java:1035)
	at androidx.media3.exoplayer.offline.DownloadManager.onDownloadUpdate(DownloadManager.java:635)
	at androidx.media3.exoplayer.offline.DownloadManager.handleMainMessage(DownloadManager.java:600)
	at androidx.media3.exoplayer.offline.DownloadManager.$r8$lambda$BgKJ2Nse_hhWOJ980vXMskcdoes(Unknown Source:0)
	at androidx.media3.exoplayer.offline.DownloadManager$$ExternalSyntheticLambda0.handleMessage(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8171)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

User actions: 
2023-10-11 16:29:39: MainActivity created
2023-10-11 16:29:39: MainActivity resumed
2023-10-11 16:30:48: MainActivity paused
2023-10-11 16:31:11: MainActivity resumed

Apps crash while downloading playlist from YouTube playlist (not the local one).

**Comment by maxrave-dev** [comment]
Did SimpMusic crash only when download music?

**Comment by aayushrautela** [comment]
Build version: 0.1.4-beta 
Current date: 2023-10-11 17:08:58 
Device: Google Pixel 6 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{6d8e29c 7944:com.maxrave.simpmusic/u0a591} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
	at android.app.Service.startForeground(Service.java:775)
	at androidx.media3.exoplayer.offline.DownloadService$ForegroundNotificationUpdater.update(DownloadService.java:920)
	at androidx.media3.exoplayer.offline.DownloadService$ForegroundNotificationUpdater.startPeriodicUpdates(DownloadService.java:893)
	at androidx.media3.exoplayer.offline.DownloadService.notifyDownloadChanged(DownloadService.java:810)
	at androidx.media3.exoplayer.offline.DownloadService.access$400(DownloadService.java:54)
	at androidx.media3.exoplayer.offline.DownloadService$DownloadManagerHelper.onDownloadChanged(DownloadService.java:1035)
	at androidx.media3.exoplayer.offline.DownloadManager.onDownloadUpdate(DownloadManager.java:635)
	at androidx.media3.exoplayer.offline.DownloadManager.handleMainMessage(DownloadManager.java:600)
	at androidx.media3.exoplayer.offline.DownloadManager.$r8$lambda$BgKJ2Nse_hhWOJ980vXMskcdoes(Unknown Source:0)
	at androidx.media3.exoplayer.offline.DownloadManager$$ExternalSyntheticLambda0.handleMessage(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8171)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

User actions: 
2023-10-11 17:08:55: MainActivity created
2023-10-11 17:08:56: MainActivity resumed


Also fails to open is Spotify is playing in background.

**Comment by aayushrautela** [comment]
Feel free to send me debug build for more real-life senario testing.

**Comment by aayushrautela** [comment]
Build version: 0.1.5-beta 
Current date: 2023-11-06 15:43:33 
Device: Google Pixel 6 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 125, Size: 116
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:763)
	at java.util.ArrayList.add(ArrayList.java:488)
	at com.maxrave.simpmusic.service.SimpleMediaServiceHandler.load(SimpleMediaServiceHandler.kt:671)
	at com.maxrave.simpmusic.service.SimpleMediaServiceHandler.load$default(SimpleMediaServiceHandler.kt:657)
	at com.maxrave.simpmusic.service.SimpleMediaServiceHandler$loadPlaylistOrAlbum$1.invokeSuspend(SimpleMediaServiceHandler.kt:847)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.maxrave.simpmusic.service.SimpleMediaServiceHandler.loadPlaylistOrAlbum(SimpleMediaServiceHandler.kt:846)
	at com.maxrave.simpmusic.viewModel.SharedViewModel.loadPlaylistOrAlbum(SharedViewModel.kt:1070)
	at com.maxrave.simpmusic.viewModel.SharedViewModel.access$loadPlaylistOrAlbum(SharedViewModel.kt:79)
	at com.maxrave.simpmusic.viewModel.SharedViewModel$loadMediaItemFromTrack$2.invokeSuspend(SharedViewModel.kt:654)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@545604, Dispatchers.Main.immediate]

User actions: 
2023-11-06 15:42:59: MainActivity created
2023-11-06 15:43:00: MainActivity resumed

Still crashes on a14

**Comment by maxrave-dev** [comment]
@foxjaw try to use latest version, it supported Android 14
