### ISSUE TITLE
Can't search for an artist while listening to songs

### ISSUE THREAD

**Issue by kyomi-dev** [maxrave-dev/SimpMusic#126]
**Describe the bug**
I'm unable to search for an artist while I'm listening to a song.

**To Reproduce**
1. Go to "Liked Songs"
2. Click on any song
3. Click on 'Search'
4. Search for an artist name
5. See the null error.

**Expected behavior**
It's expected to be able to go to the artist's profile while listening to a song.

**Log (Error Details)**
Build version: 0.1.4-beta 
Current date: 2023-10-14 14:08:51 
Device: Samsung SM-A035M 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner for ArtistFragment{4ee79c9} (f0dfe3be-5b21-45c6-b703-df6a8843e76f) when getView() is null i.e., before onCreateView() or after onDestroyView()
	at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:385)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment.fetchData(ArtistFragment.kt:361)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment.access$fetchData(ArtistFragment.kt:58)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment$fetchData$1.invoke$lambda$2(ArtistFragment.kt:434)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment$fetchData$1.$r8$lambda$Wywpw2Xmj6tcjY7dR4Ab1jJljnk(Unknown Source:0)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment$fetchData$1$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0$com-google-android-material-snackbar-Snackbar(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7892)
	at android.widget.TextView.performClick(TextView.java:16219)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1213)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30880)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

User actions: 
2023-10-14 14:08:01: MainActivity created
2023-10-14 14:08:02: MainActivity resumed

**Comment by stepersy** [comment]
Can you please share a screen recording of the bug, please? Thanks

**Comment by kyomi-dev** [comment]
Sure, here's the link: [SimpMusic bug](https://we.tl/t-Aga5Q795ui) 

The log message:
```
Build version: 0.1.4-beta 
Current date: 2023-10-15 17:02:50 
Device: Samsung SM-A035M 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner for ArtistFragment{5448285} (1df13c16-26c3-40af-83a6-bb04777fcc0d) when getView() is null i.e., before onCreateView() or after onDestroyView()
	at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:385)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment.fetchData(ArtistFragment.kt:361)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment.access$fetchData(ArtistFragment.kt:58)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment$fetchData$1.invoke$lambda$2(ArtistFragment.kt:434)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment$fetchData$1.$r8$lambda$Wywpw2Xmj6tcjY7dR4Ab1jJljnk(Unknown Source:0)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment$fetchData$1$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0$com-google-android-material-snackbar-Snackbar(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7892)
	at android.widget.TextView.performClick(TextView.java:16219)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1213)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30880)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

User actions: 
2023-10-15 17:02:31: MainActivity created
2023-10-15 17:02:32: MainActivity resumed
```

**Comment by stepersy** [comment]
Really strange, I don't have this problem on the app. Check it in the video 👇
https://github.com/maxrave-dev/SimpMusic/assets/94073410/c193def6-7197-4abc-aef5-12907ac04b3c

**Comment by kyomi-dev** [comment]
It's probably something related to my device. When I'm not logged in, the songs I like aren't saved. 
Also, how can I contribute with translation?

**Comment by stepersy** [comment]
Yeah, it's something related to your device. If I like a song when I'm not connected the song gets saved anyway. Check the video.

You can translate the app on Crowdin, you can find the Crowdin Page on the readme.

https://github.com/maxrave-dev/SimpMusic/assets/94073410/c0747cce-696a-4a5a-8458-f608d38380c5

**Comment by kyomi-dev** [comment]
Well, I'm gonna wait for an update. If there's anything I can do to help you figure out what happened, just let me know!

**Comment by stepersy** [comment]
Have you tried to uninstall and reinstall the app? Or cleaned the cache?

**Comment by kyomi-dev** [comment]
The error persists, sadly.
