### ISSUE TITLE
Crash on some double click when closing queue

### ISSUE THREAD

**Issue by cd-FileX** [maxrave-dev/SimpMusic#137]
**Describe the bug**
I'm not sure how it happened, but I think if you just tapped on the queue view close button and double tap somewhere while the queue is closing, the app crashes. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.
<details>
Build version: 0.1.4-beta 
Current date: 2023-10-21 10:47:12 
Device: DOOGEE S88Plus 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.IllegalArgumentException: Navigation action/destination com.maxrave.simpmusic:id/action_nowPlayingFragment_to_queueFragment cannot be found from the current destination Destination(com.maxrave.simpmusic:id/queueFragment) label=QueueFragment
	at androidx.navigation.NavController.navigate(NavController.kt:1686)
	at androidx.navigation.NavController.navigate(NavController.kt:1604)
	at androidx.navigation.NavController.navigate(NavController.kt:1586)
	at androidx.navigation.NavController.navigate(NavController.kt:1569)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment.onViewCreated$lambda$11(NowPlayingFragment.kt:791)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment.$r8$lambda$PV4i5lNnzHI91SFS1qStTRVWRjk(Unknown Source:0)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment$$ExternalSyntheticLambda21.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7155)
	at android.view.View.performClickInternal(View.java:7128)
	at android.view.View.access$3500(View.java:803)
	at android.view.View$PerformClick.run(View.java:27542)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

User actions: 
2023-10-21 10:33:02: MainActivity created
2023-10-21 10:33:03: MainActivity resumed
2023-10-21 10:33:27: MainActivity paused
2023-10-21 10:33:36: MainActivity resumed
2023-10-21 10:33:38: MainActivity paused
2023-10-21 10:38:12: MainActivity resumed
2023-10-21 10:38:25: MainActivity paused
2023-10-21 10:42:39: MainActivity resumed
2023-10-21 10:42:44: MainActivity paused
2023-10-21 10:42:49: MainActivity resumed
2023-10-21 10:42:53: MainActivity paused
2023-10-21 10:43:01: MainActivity resumed
2023-10-21 10:43:02: MainActivity paused
2023-10-21 10:43:28: MainActivity resumed
2023-10-21 10:43:29: MainActivity paused
2023-10-21 10:43:29: MainActivity resumed
2023-10-21 10:43:31: MainActivity paused
2023-10-21 10:43:43: MainActivity resumed
2023-10-21 10:43:50: MainActivity paused
2023-10-21 10:43:54: MainActivity resumed
2023-10-21 10:43:57: MainActivity paused
2023-10-21 10:44:05: MainActivity resumed
2023-10-21 10:44:06: MainActivity paused
2023-10-21 10:44:11: MainActivity resumed
2023-10-21 10:44:27: MainActivity paused
2023-10-21 10:44:34: MainActivity resumed
2023-10-21 10:44:40: MainActivity paused
2023-10-21 10:44:48: MainActivity resumed
2023-10-21 10:45:27: MainActivity paused
2023-10-21 10:45:37: MainActivity resumed
2023-10-21 10:45:45: MainActivity paused
2023-10-21 10:45:46: MainActivity resumed
2023-10-21 10:45:51: MainActivity paused
2023-10-21 10:46:15: MainActivity resumed
2023-10-21 10:46:21: MainActivity paused
2023-10-21 10:46:30: MainActivity resumed
2023-10-21 10:46:34: MainActivity paused
2023-10-21 10:46:39: MainActivity resumed

**Comment by maxrave-dev** [comment]
I have already seen this error before. I am trying to find out what caused this. Thanks for reporting <3
