### ISSUE TITLE
App reports unexpected error and asks to restart it after login to YT

### ISSUE THREAD

**Issue by OleksiyRudenko** [maxrave-dev/SimpMusic#143]
**Describe the bug**
Right after having login to YouTube the app's main screen reports unexpected error occurred and suggests to restart the app.

**To Reproduce**
1. Go to Settings
2. Click on Login to YouTube
3. Complete Google YT login flow
4. Exit Settings to the app's main screen
5. See unexpected error reported

**Expected behavior**
Normal UI on the main screen and mode of operation are expected.

**Screenshots**
![Screenshot_2023-10-29-09-15-32-60_b4450e33c7076f102e79bbedaff38911](https://github.com/maxrave-dev/SimpMusic/assets/8686631/568f6575-59b3-4df2-aa41-f09fcb1f499f)

**Log (Error Details)**
```
Build version: 0.1.4-beta 
Current date: 2023-10-29 09:05:03 
Device: OnePlus KB2005 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:418)
	at com.maxrave.simpmusic.adapter.home.chart.TrackChartAdapter.onBindViewHolder(TrackChartAdapter.kt:50)
	at com.maxrave.simpmusic.adapter.home.chart.TrackChartAdapter.onBindViewHolder(TrackChartAdapter.kt:11)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7678)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7761)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6582)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6848)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3981)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7080)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7080)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7080)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7080)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26695)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1921)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:640)
	at android.view.View.measure(View.java:26695)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26695)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:704)
	at android.view.View.measure(View.java:26695)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7080)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7080)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7080)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26695)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7080)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7080)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7080)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7080)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7080)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:827)
	at android.view.View.measure(View.java:26695)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4118)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2753)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3044)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2458)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9488)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1412)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1420)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1047)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:451)
	at android.view.Choreographer.doFrame(Choreographer.java:918)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1395)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8427)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

User actions: 
2023-10-29 09:01:38: MainActivity created
2023-10-29 09:01:38: MainActivity resumed
```

**Comment by maxrave-dev** [comment]
Fixed in next build #91 f823b14a03ab404b275158663fb5b4d86be4e228 . Thanks for reporting and using
