### ISSUE TITLE
Crash when loading home page whilst logged in

### ISSUE THREAD

**Issue by Fern-Leaves** [maxrave-dev/SimpMusic#144]
**Describe the bug**
when I go to the home page whilst logged into youtube music, it just crashes 

**To Reproduce**
1. Login to YouTube Music in settings
2. Let the home page load
3. "an unexpected error occurred"

**Expected behavior**
the home page loads without crashing

**Screenshots**
the home page trying to load
![Screenshot_20231030-233746](https://github.com/maxrave-dev/SimpMusic/assets/56755065/5370b9b1-a369-467b-b30e-b15d109191a9)
crash
![Screenshot_20231030-233536](https://github.com/maxrave-dev/SimpMusic/assets/56755065/76a801ce-c12e-4281-b8df-49ec0e5345a0)

**Log (Error Details)**

Build version: 0.1.4-beta 
Current date: 2023-10-30 23:33:11 
Device: Google Pixel 7 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:418)
	at com.maxrave.simpmusic.adapter.home.chart.TrackChartAdapter.onBindViewHolder(TrackChartAdapter.kt:50)
	at com.maxrave.simpmusic.adapter.home.chart.TrackChartAdapter.onBindViewHolder(TrackChartAdapter.kt:11)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7678)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7761)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6582)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6848)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3981)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1240)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27122)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1921)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:640)
	at android.view.View.measure(View.java:27122)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27122)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:704)
	at android.view.View.measure(View.java:27122)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27122)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4182)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2759)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3086)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

User actions: 
2023-10-30 23:32:52: MainActivity created
2023-10-30 23:32:52: MainActivity resumed

**Comment by hussainalhaddad** [comment]
Same thing happened to me, I had to clear the app data to get it working again

**Comment by stepersy** [comment]
Try clearing the cache.
