### ISSUE TITLE
Crash when I mive between taps

### ISSUE THREAD

**Issue by Kobmasa99** [maxrave-dev/SimpMusic#146]
**Describe the bug**
Build version: 0.1.4-beta 
Current date: 2023-11-02 12:47:58 
Device: Google Pixel 6 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:418)
	at com.maxrave.simpmusic.adapter.home.chart.TrackChartAdapter.onBindViewHolder(TrackChartAdapter.kt:50)
	at com.maxrave.simpmusic.adapter.home.chart.TrackChartAdapter.onBindViewHolder(TrackChartAdapter.kt:11)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7678)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7761)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6582)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6848)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3981)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1240)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27122)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1921)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:640)
	at android.view.View.measure(View.java:27122)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27122)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:704)
	at android.view.View.measure(View.java:27122)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27122)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
	at android.view.View.measure(View.java:27122)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4182)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2759)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3086)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

User actions: 
2023-11-02 12:47:43: MainActivity created
2023-11-02 12:47:44: MainActivity resumed

**To Reproduce**
1. Go to library 
2. Click on playlist 
3. See error

**Expected behavior**
The app crashes

**Screenshots**
![Screenshot_20231102-125329](https://github.com/maxrave-dev/SimpMusic/assets/149670952/33111a1c-15d7-4f18-a763-9a16ddd66415)

**Comment by maxrave-dev** [comment]
Did latest version fixed this bug?

**Comment by Kobmasa99** [comment]
Yes absolutely 👍🏾, thank you for the amazing work.
