### ISSUE TITLE
Immediate crash on launch after latest update

### ISSUE THREAD

**Issue by d4f5409d** [maxrave-dev/SimpMusic#15]
Android 13, 1+ 8

**Comment by maxrave-dev** [comment]
Did you use lastest build ?

**Comment by KGriss** [comment]
Same problem for me, crashing on 0.0.3 when I try to open the app. 
I am running on Android 10.

**Comment by trytomakeyouprivate** [comment]
Had it too (damn didnt know Android had Markdown formatted crash logs)

```
type: crash
osVersion: google/sunfish/sunfish:13/TQ3A.230705.001/2023072600:user/release-keys
package: com.maxrave.simpmusic:3
process: com.maxrave.simpmusic
processUptime: 364 + 351 ms
installer: com.android.packageinstaller

java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
	at com.maxrave.simpmusic.viewModel.HomeViewModel$getHomeItemList$1$job1$1.invokeSuspend(HomeViewModel.kt:52)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.maxrave.simpmusic.viewModel.HomeViewModel.getHomeItemList(HomeViewModel.kt:50)
	at com.maxrave.simpmusic.ui.fragment.home.HomeFragment.fetchResponse(HomeFragment.kt:451)
	at com.maxrave.simpmusic.ui.fragment.home.HomeFragment.fetchHomeData(HomeFragment.kt:364)
	at com.maxrave.simpmusic.ui.fragment.home.HomeFragment.onViewCreated(HomeFragment.kt:169)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1548)
	at android.app.Activity.performStart(Activity.java:8414)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3680)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@54553e6, Dispatchers.Main.immediate]
```

**Comment by LeandroPelegrini** [comment]
I had this problem, but the latest build just works fine now.

LineageOS 20 Android 13 MI6

**Comment by maxrave-dev** [comment]
Try my new 0.0.4 build, so sorry for this bugs

**Comment by Johnathan67** [comment]
> Try my new 0.0.4 build, so sorry for this bugs

Hello I am using the latest build but it's still crashing I'm on android 11 and I'm on a 32bit device (50 dollars phone brand new so ye)

**Comment by KGriss** [comment]
Installed 0.0.4 and I still crash too.
I am on Android 10 with a classic 64bit phone.

**Comment by maxrave-dev** [comment]
hmm, I test on Android 9 - x86 - 4 core - 2Gb Ram (Emulator) still working. The language is not English but my app running okay. I don't know why

**Comment by maxrave-dev** [comment]
@KGriss @d4f5409d @Johnathan67 @trytomakeyouprivate  Sorry for the bugs, I see what caused this. Try this, https://ueheduvn-my.sharepoint.com/:u:/g/personal/31211027595_ueh_edu_vn/EVyb0TkIJk1Psvayl3oBOSEBakj0arO8zzV10ADSdwav_A?e=3yq5xI , if this build works, notify me

**Comment by airon90** [comment]
v0.0.5 on MIUI 13 still crashing

**Comment by maxrave-dev** [comment]
@airon90 uninstall old version and install new version

**Comment by d4f5409d** [comment]
It works now, thanks
