### ISSUE TITLE
Don't have time to do a bug report 

### ISSUE THREAD

**Issue by skiely** [maxrave-dev/SimpMusic#150]
Build version: 0.1.5-beta 
Current date: 2023-11-06 14:02:52 
Device: Google Pixel 6 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 0
	at java.lang.String.checkBoundsBeginEnd(String.java:4466)
	at java.lang.String.substring(String.java:2517)
	at kotlin.text.StringsKt__StringsKt.substring(Strings.kt:393)
	at kotlin.text.StringsKt___StringsKt.slice(_Strings.kt:522)
	at com.maxrave.simpmusic.data.dataStore.DataStoreManager$special$$inlined$map$21$2.emit(Emitters.kt:224)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
	at androidx.datastore.core.SingleProcessDataStore$data$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:137)
	at kotlinx.coroutines.flow.FlowKt__LimitKt$dropWhile$1$1.emit(Limit.kt:40)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
	at kotlinx.coroutines.flow.FlowKt__LimitKt$dropWhile$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:115)
	at androidx.datastore.core.SingleProcessDataStore$data$1$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:114)
	at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:109)
	at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
	at androidx.datastore.core.SingleProcessDataStore$data$1.invokeSuspend(SingleProcessDataStore.kt:117)
	at androidx.datastore.core.SingleProcessDataStore$data$1.invoke(Unknown Source:8)
	at androidx.datastore.core.SingleProcessDataStore$data$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at com.maxrave.simpmusic.data.dataStore.DataStoreManager$special$$inlined$map$21.collect(SafeCollector.common.kt:114)
	at com.maxrave.simpmusic.viewModel.SettingsViewModel$getTranslationLanguage$1$1.invokeSuspend(SettingsViewModel.kt:98)
	at com.maxrave.simpmusic.viewModel.SettingsViewModel$getTranslationLanguage$1$1.invoke(Unknown Source:8)
	at com.maxrave.simpmusic.viewModel.SettingsViewModel$getTranslationLanguage$1$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at com.maxrave.simpmusic.viewModel.SettingsViewModel$getTranslationLanguage$1.invokeSuspend(SettingsViewModel.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.maxrave.simpmusic.viewModel.SettingsViewModel.getTranslationLanguage(SettingsViewModel.kt:96)
	at com.maxrave.simpmusic.ui.fragment.home.SettingsFragment.onViewCreated(SettingsFragment.kt:126)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1a60ec5, Dispatchers.Main.immediate]

User actions: 
2023-11-06 14:01:59: MainActivity created
2023-11-06 14:01:59: MainActivity resumed

**Comment by maxrave-dev** [comment]
Go to App Info of SimpMusic, scroll to change language, and change to your latest language. Open app again

**Comment by skiely** [comment]
Ok thanks but now when I click on settings I get this

Build version: 0.1.5-beta
Current date: 2023-11-06 14:28:31
Device: Google Pixel 6
OS version: Android 14 (SDK 34)

Stack trace:
java.lang.ArrayIndexOutOfBoundsException: length=11; index=-1
 at
com.maxrave.simpmusic.ui.fragment.home.SettingsFragment$onViewCreated$8.invoke(SettingsFragment.kt:178)
 at
com.maxrave.simpmusic.ui.fragment.home.SettingsFragment$onViewCreated$8.invoke(SettingsFragment.kt:176)
 at
com.maxrave.simpmusic.ui.fragment.home.SettingsFragment$sam$androidx_lifecycle_Observer$0.onChanged(Unknown
Source:2)
 at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
 at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
 at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
 at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
 at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
 at android.os.Handler.handleCallback(Handler.java:958)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:205)
 at android.os.Looper.loop(Looper.java:294)
 at android.app.ActivityThread.main(ActivityThread.java:8194)
 at java.lang.reflect.Method.invoke(Native Method)
 at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

User actions:
2023-11-06 14:28:17: MainActivity created
2023-11-06 14:28:17: MainActivity resumed

**Comment by maxrave-dev** [comment]
![Screenshot_20231106-210625_Cài_đặt.png](https://github.com/maxrave-dev/SimpMusic/assets/113747128/e6cc9d28-db8c-4a21-b714-dd6421f378f0)

In this
