### ISSUE TITLE
Crash when opening settings

### ISSUE THREAD

**Issue by teemue** [maxrave-dev/SimpMusic#152]
**Describe the bug**
The app crashes immediately after clicking the settings gear. 0.1.5-beta.

```11-06 20:03:40.117 32188 32188 E AndroidRuntime: FATAL EXCEPTION: main
11-06 20:03:40.117 32188 32188 E AndroidRuntime: Process: com.maxrave.simpmusic, PID: 32188
11-06 20:03:40.117 32188 32188 E AndroidRuntime: java.lang.StringIndexOutOfBoundsException: length=0; index=2
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at java.lang.String.substring(String.java:2060)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlin.text.StringsKt__StringsKt.substring(Strings.kt:393)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlin.text.StringsKt___StringsKt.slice(_Strings.kt:522)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at com.maxrave.simpmusic.data.dataStore.DataStoreManager$special$$inlined$map$21$2.emit(Emitters.kt:224)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at androidx.datastore.core.SingleProcessDataStore$data$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:137)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.flow.FlowKt__LimitKt$dropWhile$1$1.emit(Limit.kt:40)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.flow.FlowKt__LimitKt$dropWhile$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:115)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at androidx.datastore.core.SingleProcessDataStore$data$1$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:114)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:109)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at androidx.datastore.core.SingleProcessDataStore$data$1.invokeSuspend(SingleProcessDataStore.kt:117)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at androidx.datastore.core.SingleProcessDataStore$data$1.invoke(Unknown Source:8)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at androidx.datastore.core.SingleProcessDataStore$data$1.invoke(Unknown Source:4)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at com.maxrave.simpmusic.data.dataStore.DataStoreManager$special$$inlined$map$21.collect(SafeCollector.common.kt:114)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at com.maxrave.simpmusic.viewModel.SettingsViewModel$getTranslationLanguage$1$1.invokeSuspend(SettingsViewModel.kt:98)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at com.maxrave.simpmusic.viewModel.SettingsViewModel$getTranslationLanguage$1$1.invoke(Unknown Source:8)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at com.maxrave.simpmusic.viewModel.SettingsViewModel$getTranslationLanguage$1$1.invoke(Unknown Source:4)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at com.maxrave.simpmusic.viewModel.SettingsViewModel$getTranslationLanguage$1.invokeSuspend(SettingsViewModel.kt:97)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at com.maxrave.simpmusic.viewModel.SettingsViewModel.getTranslationLanguage(SettingsViewModel.kt:96)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at com.maxrave.simpmusic.ui.fragment.home.SettingsFragment.onViewCreated(SettingsFragment.kt:126)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
11-06 20:03:40.117 32188 32188 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
11-06 20:03:40.118 32188 32188 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
11-06 20:03:40.118 32188 32188 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
11-06 20:03:40.118 32188 32188 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
11-06 20:03:40.118 32188 32188 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-06 20:03:40.118 32188 32188 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-06 20:03:40.118 32188 32188 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:233)
11-06 20:03:40.118 32188 32188 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8063)
11-06 20:03:40.118 32188 32188 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-06 20:03:40.118 32188 32188 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
11-06 20:03:40.118 32188 32188 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
11-06 20:03:40.118 32188 32188 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7e69f6, Dispatchers.Main.immediate]
```

**Comment by andronedev** [comment]
same

**Comment by amitkori1** [comment]
Build version: 0.1.5-beta 
Current date: 2023-11-07 01:42:05 
Device: Xiaomi M2101K6I 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 0
	at java.lang.String.checkBoundsBeginEnd(String.java:4466)
	at java.lang.String.substring(String.java:2517)
	at kotlin.text.StringsKt__StringsKt.substring(Strings.kt:393)
	at kotlin.text.StringsKt___StringsKt.slice(_Strings.kt:522)
	at com.maxrave.simpmusic.data.dataStore.DataStoreManager$special$$inlined$map$21$2.emit(Emitters.kt:224)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
	at androidx.datastore.core.SingleProcessDataStore$data$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:137)
	at kotlinx.coroutines.flow.FlowKt__LimitKt$dropWhile$1$1.emit(Limit.kt:40)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
	at kotlinx.coroutines.flow.FlowKt__LimitKt$dropWhile$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:115)
	at androidx.datastore.core.SingleProcessDataStore$data$1$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:114)
	at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:109)
	at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
	at androidx.datastore.core.SingleProcessDataStore$data$1.invokeSuspend(SingleProcessDataStore.kt:117)
	at androidx.datastore.core.SingleProcessDataStore$data$1.invoke(Unknown Source:8)
	at androidx.datastore.core.SingleProcessDataStore$data$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at com.maxrave.simpmusic.data.dataStore.DataStoreManager$special$$inlined$map$21.collect(SafeCollector.common.kt:114)
	at com.maxrave.simpmusic.viewModel.SettingsViewModel$getTranslationLanguage$1$1.invokeSuspend(SettingsViewModel.kt:98)
	at com.maxrave.simpmusic.viewModel.SettingsViewModel$getTranslationLanguage$1$1.invoke(Unknown Source:8)
	at com.maxrave.simpmusic.viewModel.SettingsViewModel$getTranslationLanguage$1$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at com.maxrave.simpmusic.viewModel.SettingsViewModel$getTranslationLanguage$1.invokeSuspend(SettingsViewModel.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.maxrave.simpmusic.viewModel.SettingsViewModel.getTranslationLanguage(SettingsViewModel.kt:96)
	at com.maxrave.simpmusic.ui.fragment.home.SettingsFragment.onViewCreated(SettingsFragment.kt:126)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@270586, Dispatchers.Main.immediate]

User actions: 
2023-11-07 01:41:54: MainActivity created
2023-11-07 01:41:55: MainActivity resumed
