### ISSUE TITLE
Settings bug

### ISSUE THREAD

**Issue by BlackSparkz** [maxrave-dev/SimpMusic#154]
**Describe the bug**
App is crashing when click on settings icon 

**To Reproduce**
1. Open app
2. Click on setting icon 
3. See error

**Screenshots**
![Screenshot_20231107_073403_SimpMusic.png](https://github.com/maxrave-dev/SimpMusic/assets/78287172/01891d08-4d45-4120-896f-10d73778fe0d)

**Log (Error Details)**
Build version: 0.1.5 
Current date: 2023-11-07 07:26:38 
Device: Samsung SM-A346E 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=11; index=-1
	at com.maxrave.simpmusic.ui.fragment.home.SettingsFragment$onViewCreated$8.invoke(SettingsFragment.kt:178)
	at com.maxrave.simpmusic.ui.fragment.home.SettingsFragment$onViewCreated$8.invoke(SettingsFragment.kt:176)
	at com.maxrave.simpmusic.ui.fragment.home.SettingsFragment$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

User actions: 
2023-11-07 07:25:11: MainActivity created
2023-11-07 07:25:11: MainActivity resumed

**Comment by maxrave-dev** [comment]
Change per-app language and reopen app
https://android-developers.googleblog.com/2022/11/per-app-language-preferences-part-1.html

**Comment by Shivamhobbyist** [comment]
> Change per-app language and reopen app
> https://android-developers.googleblog.com/2022/11/per-app-language-preferences-part-1.html

Still not fixx

**Comment by maxrave-dev** [comment]
Check out latest release

**Comment by Shivamhobbyist** [comment]
> Check out latest release 

Now it's fixed 👍

**Comment by Shivamhobbyist** [comment]
> Check out latest release 

Here a new problem

https://www.jiocloud.com/l/?u=65l8ySi4Xe_-n_vevjHM4dzZo-1GgiEQnUoNMkZJ4bA=XPz




Build version: 0.1.5 
Current date: 2023-11-07 15:01:27 
Device: Samsung SM-A346E 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at com.maxrave.simpmusic.viewModel.SharedViewModel.getActiveLyrics(SharedViewModel.kt:827)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment$onViewCreated$8$1$job5$1$1.emit(NowPlayingFragment.kt:550)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment$onViewCreated$8$1$job5$1$1.emit(NowPlayingFragment.kt:537)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
	at kotlinx.coroutines.flow.ReadonlySharedFlow.collect(Unknown Source:2)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment$onViewCreated$8$1$job5$1.invokeSuspend(NowPlayingFragment.kt:537)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.maxrave.simpmusic.ui.fragment.player.NowPlayingFragment.onViewCreated(NowPlayingFragment.kt:458)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@57cb98a, Dispatchers.Main.immediate]

User actions: 
2023-11-07 14:57:15: MainActivity created
2023-11-07 14:57:16: MainActivity resumed
