### ISSUE TITLE
Can't delete song from created playlist

### ISSUE THREAD

**Issue by DeadSecTr** [maxrave-dev/SimpMusic#155]
Build version: 0.1.5 
Current date: 2023-11-07 03:48:29 
Device: Motorola moto g42 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index 16 out of bounds for length 16
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at com.maxrave.simpmusic.ui.fragment.other.LocalPlaylistFragment$onViewCreated$5.onOptionClick$lambda$0(LocalPlaylistFragment.kt:193)
	at com.maxrave.simpmusic.ui.fragment.other.LocalPlaylistFragment$onViewCreated$5.$r8$lambda$SGAKfN1g64BhtWFqbXiIEzXlYAI(Unknown Source:0)
	at com.maxrave.simpmusic.ui.fragment.other.LocalPlaylistFragment$onViewCreated$5$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7467)
	at android.view.View.performClickInternal(View.java:7444)
	at android.view.View.access$3700(View.java:840)
	at android.view.View$PerformClick.run(View.java:28831)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8098)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

User actions: 
2023-11-07 03:37:06: MainActivity created
2023-11-07 03:37:07: MainActivity resumed
2023-11-07 03:42:43: MainActivity paused
2023-11-07 03:43:28: MainActivity resumed
2023-11-07 03:44:21: MainActivity paused
2023-11-07 03:45:34: MainActivity resumed

**Comment by maxrave-dev** [comment]
I see this bug. Will fix now

**Comment by maxrave-dev** [comment]
Check latest release

**Comment by DeadSecTr** [comment]
Still not working bro....
