### ISSUE TITLE
Artist Profile error "null"

### ISSUE THREAD

**Issue by dPandl** [maxrave-dev/SimpMusic#184]
**Describe the bug**
When you go to the artist profile, you get the error message "null" and the page doesn't open.

I don't know if the error is "null" in English because the app crashes when I try to change the language, sorry.

**To Reproduce**
1. Search for any Artist
2. Click on his Profile
3. See error "null" on the bottom of the screen

**Expected behavior**
It should show the Artist Page.

**Screenshots**
![IMG_20231130_234437](https://github.com/maxrave-dev/SimpMusic/assets/35048273/abcdb8f2-cb3c-448f-9994-086598ad2795)

**Comment by walrus543** [comment]
Same issue.
Device: Oneplus 8 Pro
Android : OxygenOS 13
SimpMusic version: 0.1.6

**Comment by siggi1984** [comment]
I have the same problem. See the video.


https://github.com/maxrave-dev/SimpMusic/assets/103368536/8c66c08c-caa2-4c88-84ed-fd96f5deda30

Device: Samsung Galaxy a21s
Android 12
SimpMusic version: 0.1.6

**Comment by DarkCrypt** [comment]
> I don't know if the error is "null" in English

Yes, the error is also "null" in English.

Artist profiles are working correctly for US (content country). I have not encountered this issue. The nonworking reports look to be German.
___
> app crashes when I try to change the language

I can also confirm. User selects any language and app crashes.
_ _
Build version: 0.1.6 
Current date: 2023-12-17 23:30:18 
Device: OnePlus LE2125 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=11; index=-1
	at com.maxrave.simpmusic.ui.fragment.home.SettingsFragment$onViewCreated$31$dialog$3$alertDialog$2$1.invoke(SettingsFragment.kt:413)
	at com.maxrave.simpmusic.ui.fragment.home.SettingsFragment$onViewCreated$31$dialog$3$alertDialog$2$1.invoke(SettingsFragment.kt:411)
	at com.maxrave.simpmusic.ui.fragment.home.SettingsFragment$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:483)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:440)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
	at androidx.lifecycle.LiveData.observe(LiveData.java:205)
	at com.maxrave.simpmusic.ui.fragment.home.SettingsFragment.onViewCreated$lambda$26$lambda$25$lambda$24(SettingsFragment.kt:411)
	at com.maxrave.simpmusic.ui.fragment.home.SettingsFragment.$r8$lambda$50UbA0RIr6SDgijt-DLfM-aZR4k(Unknown Source:0)
	at com.maxrave.simpmusic.ui.fragment.home.SettingsFragment$$ExternalSyntheticLambda5.onClick(Unknown Source:6)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8423)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

User actions: 
2023-12-17 23:30:08: MainActivity created
2023-12-17 23:30:09: MainActivity resumed

**Comment by maxrave-dev** [comment]
I see this error, and trying to fix it. May be YouTube API changed something. Please be patient!

**Comment by maxrave-dev** [comment]
Fixed, try nightly version in Action Tab

**Comment by DarkCrypt** [comment]
Nightly version is working correctly. 👍
