### ISSUE TITLE
App crashed while playing video

### ISSUE THREAD

**Issue by NikunjKhangwal** [maxrave-dev/SimpMusic#193]
**Describe the bug**
The app crashed randomly while playing a video. This happened in debug build

**To Reproduce**
Just tapping on a video to play

**Expected behavior**
The video should play

**Log (Error Details)**
Build version: 0.1.6 
Current date: 2023-12-20 16:55:20 
Device: Xiaomi M2004J19PI 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.NullPointerException
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment.getBinding(ArtistFragment.kt:70)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment.access$getBinding(ArtistFragment.kt:66)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment$onViewCreated$22$1$artistJob$1$1.invokeSuspend(ArtistFragment.kt:447)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment$onViewCreated$22$1$artistJob$1$1.invoke(Unknown Source:8)
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment$onViewCreated$22$1$artistJob$1$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:217)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:8)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
	at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:235)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at kotlinx.coroutines.flow.StateFlowSlot.makePending(StateFlow.kt:284)
	at kotlinx.coroutines.flow.StateFlowImpl.updateState(StateFlow.kt:349)
	at kotlinx.coroutines.flow.StateFlowImpl.setValue(StateFlow.kt:316)
	at kotlinx.coroutines.flow.StateFlowImpl.emit(StateFlow.kt:373)
	at com.maxrave.simpmusic.viewModel.ArtistViewModel$browseArtist$1$1.emit(ArtistViewModel.kt:66)
	at com.maxrave.simpmusic.viewModel.ArtistViewModel$browseArtist$1$1.emit(ArtistViewModel.kt:65)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@16e71bc, Dispatchers.Main.immediate]

User actions: 
2023-12-20 16:53:21: MainActivity created
2023-12-20 16:53:22: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi, Is this still happening with 0.2.19?

**Comment by NikunjK8** [comment]
Seem to be fixed now, closing the issue.
