### ISSUE TITLE
If I use Finnish almost nothing plays

### ISSUE THREAD

**Issue by MeiRos** [maxrave-dev/SimpMusic#199]
**Describe the bug**
I have high bitrate, Location Finland and language Finnish and almost nothing plays. Videos works fine. Mostly when I try to play album, the loading keeps spinning on black screen. Sometimes it opens album cover but don' t show songs. When this happens and I hit the play app crashes.
When I change language to English, Spanish or German, I don't have problems.

**To Reproduce**
1. Change language to Finnish
2. Click on Suvi Teräsniska's album Tulkoon joulu on Suositellut albumit category.
3. Hit the play button next to heart symbol.
4. App should crash. Error log below.

You can also try Bilemusiikkia category.
1. Choose Hip Hop classics.
2.  It keeps loading...

**Expected behavior**
Songs should play or albums should open with songlist.
English version don't show any description just no description text. Is it possible that it causes problems? Anyway, it's with some albums only. Most of them just keeps loading and no error logs.

**Screenshots**
![Screenshot_20231224_004503_SimpMusic](https://github.com/maxrave-dev/SimpMusic/assets/17142569/0b6d944e-cdc4-465e-8d5d-fc187e71d252)
There should be 11 kappaletta (tracks) not 0.

![Screenshot_20231224_003825_SimpMusic](https://github.com/maxrave-dev/SimpMusic/assets/17142569/828d8a2e-783e-42f8-b0a7-b48189338262)

**Log (Error Details)**

```
Build version: 0.1.7 
Current date: 2023-12-24 00:44:13 
Device: Samsung SM-S901B 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at com.maxrave.simpmusic.ui.fragment.other.AlbumFragment.onViewCreated$lambda$7(AlbumFragment.kt:194)
	at com.maxrave.simpmusic.ui.fragment.other.AlbumFragment.$r8$lambda$iAjFA2WN2KyzMdaVhhGcaqoq4Ag(Unknown Source:0)
	at com.maxrave.simpmusic.ui.fragment.other.AlbumFragment$$ExternalSyntheticLambda4.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:8043)
	at android.view.View.performClickInternal(View.java:8020)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31850)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

User actions: 
2023-12-24 00:39:14: MainActivity created
2023-12-24 00:39:14: MainActivity resumed
```

**Comment by teemue** [comment]
Related #157

**Comment by maxrave-dev** [comment]
Anyone know any free VPN which have a Finnish server? I need to know YouTube API return what in your country and fix it

**Comment by teemue** [comment]
> Anyone know any free VPN which have a Finnish server? I need to know YouTube API return what in your country and fix it

I'm happy to provide you with such information if you tell me how to scrape it :-)

**Comment by MeiRos** [comment]
> Anyone know any free VPN which have a Finnish server? I need to know YouTube API return what in your country and fix it

Here https://campaigns.f-secure.com/vpn/pm/en/?gad_source=1#try is free vpn to try for 5 days. I think that's a reliable Finnish company. One minus. No Linux support. ```
Supported platforms
Windows 8.1, Windows 10, Windows 11
macOS 10.15 or later
iOS 14.2 or later
Android 8.0 or later
```

@teemue
Oops. I didn't search well. Just read latest issues. 🙈

**Comment by MeiRos** [comment]
@maxrave-dev I can use Monero to pay 1 month Mullvad VPN for you. If you still need a VPN.

**Comment by maxrave-dev** [comment]
Explained in #241
