### ISSUE TITLE
App is Crashing v0.0.4

### ISSUE THREAD

**Issue by RandomNam3** [maxrave-dev/SimpMusic#20]
Hello,
after the update to the 0.0.4 the app unfortunately still crashes, immediately after the start.

```
type: crash
osVersion: google/cheetah/cheetah:13/TQ3A.230705.001/2023072600:user/release-keys
package: com.maxrave.simpmusic:4
process: com.maxrave.simpmusic
processUptime: 218 + 245 ms
installer: com.looker.droidify

java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
	at com.maxrave.simpmusic.viewModel.HomeViewModel$getHomeItemList$3.invokeSuspend(HomeViewModel.kt:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.maxrave.simpmusic.viewModel.HomeViewModel.<init>(HomeViewModel.kt:55)
	at com.maxrave.simpmusic.DaggerSimpMusicApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerSimpMusicApplication_HiltComponents_SingletonC.java:782)
	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:102)
	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.kt:90)
	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:114)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:53)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
	at com.maxrave.simpmusic.ui.fragment.home.HomeFragment.getViewModel(HomeFragment.kt:48)
	at com.maxrave.simpmusic.ui.fragment.home.HomeFragment.initObserver(HomeFragment.kt:225)
	at com.maxrave.simpmusic.ui.fragment.home.HomeFragment.onViewCreated(HomeFragment.kt:81)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1548)
	at android.app.Activity.performStart(Activity.java:8414)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3680)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ed22cd4, Dispatchers.Main.immediate]

```

**Comment by VladekTw** [comment]
https://paste.crdroid.net/sxMNDV

**Comment by owencz1998** [comment]
Same can't open app on my s23 ultra

**Comment by maxrave-dev** [comment]
@RandomNam3 @VladekTw  @owencz1998 Sorry for the bugs, I see what caused this. Try this, https://ueheduvn-my.sharepoint.com/:u:/g/personal/31211027595_ueh_edu_vn/EVyb0TkIJk1Psvayl3oBOSEBakj0arO8zzV10ADSdwav_A?e=3yq5xI , if this build works, notify me

**Comment by owencz1998** [comment]
No still doesn't work mate just flashes and closes @maxrave-dev

**Comment by maxrave-dev** [comment]
@owencz1998 https://drive.google.com/file/d/1WS3KhW0A84VWU5t8bbBvtehvg4elQBBE/view?usp=sharing try this

**Comment by owencz1998** [comment]
@maxrave-dev still not working unfortunately

**Comment by maxrave-dev** [comment]
> @maxrave-dev still not working unfortunately 

After check logs, i see it caused by locale. But i try to resolve, it still not work. But i can change locale for test haizzz

**Comment by owencz1998** [comment]
@maxrave-dev worth a shot dude hopefully this will work also have u checked the discussion mate

**Comment by maxrave-dev** [comment]
@owencz1998 did you uninstall and reinstall?

**Comment by maxrave-dev** [comment]
@RandomNam3 @VladekTw @

**Comment by owencz1998** [comment]
No just updated but I'll give it ago @maxrave-dev

**Comment by RandomNam3** [comment]
It works for me now (v0.0.5).

:D

**Comment by owencz1998** [comment]
Me to @maxrave-dev 😅😁

**Comment by mondlicht-und-sterne** [comment]
Yes, the 0.0.5-beta works now.
Thx for fix 👍

**Comment by VladekTw** [comment]
> @RandomNam3 @VladekTw @

Thanks, new version work.
