### ISSUE TITLE
Crash on app open

### ISSUE THREAD

**Issue by cd-FileX** [maxrave-dev/SimpMusic#208]
**Describe the bug**
The app crashing after upgrading from 0.1.4 to 0.1.7. Clearing cash is useless.

**To Reproduce**
1. /

**Expected behavior**

**Screenshots**

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.
<details>
Build version: 0.1.7 
Current date: 2024-01-01 13:53:08 
Device: DOOGEE S88Plus 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 2 path $
	at com.google.gson.Gson.fromJson(Gson.java:1238)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:1014)
	at com.maxrave.simpmusic.di.LocalServiceModule$provideMusicDatabase$1.migrate(LocalServiceModule.kt:47)
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.kt:90)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.kt:253)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:417)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:232)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:190)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.kt:632)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.kt:451)
	at androidx.room.RoomDatabase.query(RoomDatabase.kt:480)
	at androidx.room.util.DBUtil.query(DBUtil.kt:75)
	at com.maxrave.simpmusic.data.db.DatabaseDao_Impl$83.call(DatabaseDao_Impl.java:2742)
	at com.maxrave.simpmusic.data.db.DatabaseDao_Impl$83.call(DatabaseDao_Impl.java:2738)
	at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d5d392b, Dispatchers.Main.immediate]
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:358)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 24 more

User actions: 
2024-01-01 13:48:45: MainActivity created
2024-01-01 13:48:46: MainActivity resumed

**Comment by maxrave-dev** [comment]
Yes, some time I missed something
