### ISSUE TITLE
Can't play the music

### ISSUE THREAD

**Issue by IkisIvy** [maxrave-dev/SimpMusic#231]
**Describe the bug**
The albums or followed lists aren't played and the system is reseted.

**To Reproduce**
1. Go to any albums or followed lists
2. Click on play
3. See error

**Expected behavior**

**Screenshots**

**Log (Error Details)**
Build version: 0.1.8 
Current date: 2024-01-23 15:37:24 
Device: OPPO CPH2081 
OS version: Android 9 (SDK 28) 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setCallback(android.graphics.drawable.Drawable$Callback)' on a null object reference
	at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:141)
	at android.graphics.drawable.TransitionDrawable.<init>(TransitionDrawable.java:97)
	at android.graphics.drawable.TransitionDrawable.<init>(TransitionDrawable.java:79)
	at com.maxrave.simpmusic.ui.fragment.other.PlaylistFragment$fetchDataWithRadio$1$1$1$1.invoke(PlaylistFragment.kt:833)
	at com.maxrave.simpmusic.ui.fragment.other.PlaylistFragment$fetchDataWithRadio$1$1$1$1.invoke(PlaylistFragment.kt:826)
	at com.maxrave.simpmusic.ui.fragment.other.PlaylistFragment$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:7225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)

User actions: 
2024-01-23 15:26:38: MainActivity created
2024-01-23 15:26:39: MainActivity resumed
2024-01-23 15:26:59: MainActivity paused
2024-01-23 15:37:02: MainActivity resumed

**Comment by maxrave-dev** [comment]
How often did you got this error?

**Comment by IkisIvy** [comment]
Until now this error still appears.  I can still find and listen to music, as well as choose to listen to certain albums.  However, when I want to listen to music on certain albums, the same error occurs and the application has to be restarted.  I tried deleting and redownloading but still no change.
