### ISSUE TITLE
App crashes on viewing a certain album

### ISSUE THREAD

**Issue by ZOASR** [maxrave-dev/SimpMusic#248]
**Describe the bug**
Navigating to the album from the artist page crashes the app every time
https://music.youtube.com/playlist?list=OLAK5uy_mlF1FNbdMoXA5WC6IQ69oXe7i3o5LCOB0

Note: issue stopped reproducing after several app restarts, will still keep issue open if anyone encounters the same issue

**To Reproduce**
1. open album playlist at https://music.youtube.com/playlist?list=OLAK5uy_mlF1FNbdMoXA5WC6IQ69oXe7i3o5LCOB0
2. App crashes

**Expected behavior**
Album should be viewed normally

**Log (Error Details)**
issue stopped happening after a certain number of app restarts so i can't grab the logs anymore.

**Comment by maxrave-dev** [comment]
NO CRASH WHEN I OPEN, GIVE ME CRASH LOG

**Comment by ZOASR** [comment]
the crash  happened again, this time i grabbed the logs


Build version: 0.1.8 
Current date: 2024-02-19 10:43:02 
Device: Realme RMX3263 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.NullPointerException
	at com.maxrave.simpmusic.ui.fragment.other.AlbumFragment.getBinding(AlbumFragment.kt:66)
	at com.maxrave.simpmusic.ui.fragment.other.AlbumFragment.access$getBinding(AlbumFragment.kt:60)
	at com.maxrave.simpmusic.ui.fragment.other.AlbumFragment$onViewCreated$1$1.emit(AlbumFragment.kt:93)
	at com.maxrave.simpmusic.ui.fragment.other.AlbumFragment$onViewCreated$1$1.emit(AlbumFragment.kt:92)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
	at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:235)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at kotlinx.coroutines.flow.StateFlowSlot.makePending(StateFlow.kt:284)
	at kotlinx.coroutines.flow.StateFlowImpl.updateState(StateFlow.kt:349)
	at kotlinx.coroutines.flow.StateFlowImpl.setValue(StateFlow.kt:316)
	at com.maxrave.simpmusic.viewModel.AlbumViewModel$insertAlbum$1$1.emit(AlbumViewModel.kt:82)
	at com.maxrave.simpmusic.viewModel.AlbumViewModel$insertAlbum$1$1.emit(AlbumViewModel.kt:81)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7950)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@62223f7, Dispatchers.Main.immediate]

User actions: 
2024-02-19 10:42:30: MainActivity created
2024-02-19 10:42:31: MainActivity resumed

**Comment by ZOASR** [comment]
@maxrave-dev sorry to mention but i can't reopen the issue and i thought you might wanna reopen it
