### ISSUE TITLE
Crashed on opening app

### ISSUE THREAD

**Issue by f3vkx** [maxrave-dev/SimpMusic#261]
**Describe the bug**

**To Reproduce**
1. Just opened app. 

**Log (Error Details)**
Build version: 0.2.0 
Current date: 2024-02-17 12:02:21 
Device: Google Pixel 7 Pro 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:562)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	... 3 more
Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: Session rejected the connection request.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.maxrave.simpmusic.service.SimpleMediaService.onCreate$lambda$2(SimpleMediaService.kt:110)
	at com.maxrave.simpmusic.service.SimpleMediaService.$r8$lambda$aYQNUK0m9DwoO51tcNDQ3EQ5guk(Unknown Source:0)
	at com.maxrave.simpmusic.service.SimpleMediaService$$ExternalSyntheticLambda2.run(Unknown Source:2)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at androidx.media3.session.MediaControllerHolder.maybeSetException(MediaControllerHolder.java:67)
	at androidx.media3.session.MediaControllerHolder.onRejected(MediaControllerHolder.java:57)
	at androidx.media3.session.MediaController.release(MediaController.java:530)
	at androidx.media3.session.MediaControllerImplBase$$ExternalSyntheticLambda41.run(Unknown Source:2)
	at androidx.media3.common.util.Util.postOrRun(Util.java:761)
	at androidx.media3.session.MediaController.runOnApplicationLooper(MediaController.java:1940)
	at androidx.media3.session.MediaControllerStub.lambda$onDisconnected$1(MediaControllerStub.java:96)
	at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda4.run(Unknown Source:0)
	at androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$12(MediaControllerStub.java:310)
	at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda13.run(Unknown Source:4)
	at androidx.media3.common.util.Util.postOrRun(Util.java:761)
	at androidx.media3.session.MediaControllerStub.dispatchControllerTaskOnHandler(MediaControllerStub.java:302)
	at androidx.media3.session.MediaControllerStub.onDisconnected(MediaControllerStub.java:94)
	at androidx.media3.session.MediaSessionService$MediaSessionServiceStub.lambda$connect$0$androidx-media3-session-MediaSessionService$MediaSessionServiceStub(MediaSessionService.java:729)
	at androidx.media3.session.MediaSessionService$MediaSessionServiceStub$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	... 5 more
Caused by: java.lang.SecurityException: Session rejected the connection request.
	... 25 more

User actions: 
2024-02-17 11:59:10: MainActivity created
2024-02-17 11:59:10: MainActivity resumed

![Screenshot_20240217_120355](https://github.com/maxrave-dev/SimpMusic/assets/152092571/83976c7c-1eb5-42b2-8415-003e5342b7ff)

**Comment by maxrave-dev** [comment]
Try to reinstall
