### ISSUE TITLE
Crash when starting music (v0.0.5)

### ISSUE THREAD

**Issue by RandomNam3** [maxrave-dev/SimpMusic#29]
Hello,
Unfortunately, when I try to start playing music, the app crashes.

```
type: crash
osVersion: google/cheetah/cheetah:13/TQ3A.230705.001/2023072600:user/release-keys
package: com.maxrave.simpmusic:5
process: com.maxrave.simpmusic
processUptime: 8018 + 228 ms
installer: io.github.muntashirakon.AppManager

java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. Expected identity hash: 584c84929cc872dea0e4fa287c3c6809, found: 0b79be7c71e3cd87102b15f8daf00fd9
	at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.kt:147)
	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.kt:128)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.kt:287)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:434)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:323)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:232)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:190)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
	at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.kt:528)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.kt:517)
	at com.maxrave.simpmusic.data.db.DatabaseDao_Impl$28.call(DatabaseDao_Impl.java:601)
	at com.maxrave.simpmusic.data.db.DatabaseDao_Impl$28.call(DatabaseDao_Impl.java:598)
	at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:65)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.kt:36)
	at androidx.room.TransactionExecutor.$r8$lambda$AympDHYBb78s7_N_9gRsXF0sHiw(Unknown Source:0)
	at androidx.room.TransactionExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@790b6d2, Dispatchers.Main.immediate]

```

**Comment by maxrave-dev** [comment]
Clear data or uninstall and reinstall because conflict database

**Comment by RandomNam3** [comment]
That would also have been too easy. I reinstalled the app and the same problem. I also noticed that other YT Music front ends are currently having similar difficulties.

**Comment by maxrave-dev** [comment]
When I test in debug, if I updated database, it will cause this error. Please, don't use backup file from 0.0.3 before. Make sure SimpMusic is removed clearly, then reinstall. Hope it helpful for you! Cheer <3

**Comment by RandomNam3** [comment]
There is a backup function? ^^`
