### ISSUE TITLE
Crashing and inability to properly download songs

### ISSUE THREAD

**Issue by n3rdcub** [maxrave-dev/SimpMusic#30]
App crashes at random during playback, and songs are downloaded 10% of the time if even that. 
Regions is US

**Comment by n3rdcub** [comment]
```
type: crash
osVersion: google/panther/panther:13/TQ3A.230705.001/2023072600:user/release-keys
package: com.maxrave.simpmusic:5
process: com.maxrave.simpmusic
processUptime: 287 + 153 ms
installer: com.android.packageinstaller

java.lang.IndexOutOfBoundsException
	at androidx.media3.common.Timeline$1.getWindow(Timeline.java:993)
	at androidx.media3.common.Timeline.getWindow(Timeline.java:1114)
	at androidx.media3.common.BasePlayer.getMediaItemAt(BasePlayer.java:369)
	at com.maxrave.simpmusic.service.SimpleMediaServiceHandler.getMediaItemWithIndex(SimpleMediaServiceHandler.kt:60)
	at com.maxrave.simpmusic.service.test.source.FetchQueue$onStartCommand$1$1.emit(FetchQueue.kt:56)
	at com.maxrave.simpmusic.service.test.source.FetchQueue$onStartCommand$1$1.emit(FetchQueue.kt:46)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
	at kotlinx.coroutines.flow.ReadonlyStateFlow.collect(Unknown Source:2)
	at com.maxrave.simpmusic.service.test.source.FetchQueue$onStartCommand$1.invokeSuspend(FetchQueue.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2aab0fd, Dispatchers.Main]

```

**Comment by maxrave-dev** [comment]
Please try my latest build. If it still not work, please report to me

**Comment by TakiShiwa** [comment]
It crashed for me

```
{"REPORT_ID":"3974d412-1ea2-4f64-bcce-1ee5cd9fcd1b","APP_VERSION_CODE":6,"APP_VERSION_NAME":"0.1.0-beta","PACKAGE_NAME":"com.maxrave.simpmusic","FILE_PATH":"\/data\/user\/0\/com.maxrave.simpmusic\/files","PHONE_MODEL":"CPH2373","BRAND":"OPPO","PRODUCT":"CPH2373","ANDROID_VERSION":"13","BUILD":{"BOARD":"bengal","BOOTLOADER":"unknown","BRAND":"OPPO","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"OP530DL1","DISPLAY":"CPH2373_11_F.62","FINGERPRINT":"OPPO\/CPH2373\/OP530DL1:13\/TP1A.220905.001\/R.10f44f4-39835-39836:user\/release-keys","HARDWARE":"qcom","HOST":"dg02-pool03-kvm156","ID":"TP1A.220905.001","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"OPPO","MODEL":"CPH2373","ODM_SKU":"unknown","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"CPH2373","RADIO":"unknown","SKU":"unknown","SOC_MANUFACTURER":"QTI","SOC_MODEL":"SM6225","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1685669913000,"TYPE":"user","UNKNOWN":"unknown","USER":"root","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"R.10f44f4-39835-39836","KNOWN_CODENAMES":"{HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}","MEDIA_PERFORMANCE_CLASS":0,"PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"13","RELEASE_OR_CODENAME":"13","RELEASE_OR_PREVIEW_DISPLAY":"13","SDK":"33","SDK_INT":33,"SECURITY_PATCH":"2023-06-05"}},"TOTAL_MEM_SIZE":115871657984,"AVAILABLE_MEM_SIZE":43017519104,"BUILD_CONFIG":{"APPLICATION_ID":"com.maxrave.simpmusic","BUILD_TYPE":"release","DEBUG":false,"VERSION_CODE":6,"VERSION_NAME":"0.1.0-beta"},"CUSTOM_DATA":{},"IS_SILENT":false,"STACK_TRACE":"java.lang.IndexOutOfBoundsException\n\tat androidx.media3.common.Timeline$1.getWindow(Timeline.java:993)\n\tat androidx.media3.common.Timeline.getWindow(Timeline.java:1114)\n\tat androidx.media3.common.BasePlayer.getMediaItemAt(BasePlayer.java:369)\n\tat com.maxrave.simpmusic.service.SimpleMediaServiceHandler.getMediaItemWithIndex(SimpleMediaServiceHandler.kt:52)\n\tat com.maxrave.simpmusic.service.test.source.FetchQueue$onStartCommand$1$1.emit(FetchQueue.kt:50)\n\tat com.maxrave.simpmusic.service.test.source.FetchQueue$onStartCommand$1$1.emit(FetchQueue.kt:46)\n\tat kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)\n\tat kotlinx.coroutines.flow.ReadonlyStateFlow.collect(Unknown Source:2)\n\tat com.maxrave.simpmusic.service.test.source.FetchQueue$onStartCommand$1.invokeSuspend(FetchQueue.kt:46)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)\n\tat android.os.Handler.handleCallback(Handler.java:942)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:240)\n\tat android.os.Looper.loop(Looper.java:351)\n\tat android.app.ActivityThread.main(ActivityThread.java:8381)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)\n\tSuppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1161cc2, Dispatchers.Main]\n","INITIAL_CONFIGURATION":{"colorMode":5,"densityDpi":408,"fontScale":0.9,"fontWeightAdjustment":0,"hardKeyboardHidden":"HARDKEYBOARDHIDDEN_YES","keyboard":"KEYBOARD_NOKEYS","keyboardHidden":"KEYBOARDHIDDEN_NO","locale":"en_US","mcc":404,"mnc":76,"navigation":"NAVIGATION_NONAV","navigationHidden":"NAVIGATIONHIDDEN_YES","orientation":"ORIENTATION_PORTRAIT","screenHeightDp":883,"screenLayout":"SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO","screenWidthDp":423,"seq":7599,"smallestScreenWidthDp":423,"touchscreen":"TOUCHSCREEN_FINGER","uiMode":"UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO","userSetLocale":true,"mOplusExtraConfiguration":"mThemeChanged= 0, mThemeChangedFlags= 0, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 3479899189152842033, mMaterialColor= 100040000, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 31f4, mFoldingAngle = -1.0, mIconPackName= , mDarkModeBackgroundMaxL= 0.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1, mOplusChangedConfigs= 0, OpSans= 4096, mFlag= 0"},"CRASH_CONFIGURATION":{"colorMode":5,"densityDpi":408,"fontScale":0.9,"fontWeightAdjustment":0,"hardKeyboardHidden":"HARDKEYBOARDHIDDEN_YES","keyboard":"KEYBOARD_NOKEYS","keyboardHidden":"KEYBOARDHIDDEN_NO","locale":"en_US","mcc":404,"mnc":76,"navigation":"NAVIGATION_NONAV","navigationHidden":"NAVIGATIONHIDDEN_YES","orientation":"ORIENTATION_PORTRAIT","screenHeightDp":883,"screenLayout":"SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO","screenWidthDp":423,"seq":7599,"smallestScreenWidthDp":423,"touchscreen":"TOUCHSCREEN_FINGER","uiMode":"UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO","userSetLocale":true,"mOplusExtraConfiguration":"mThemeChanged= 0, mThemeChangedFlags= 0, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 3479899189152842033, mMaterialColor= 100040000, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 31f4, mFoldingAngle = -1.0, mIconPackName= , mDarkModeBackgroundMaxL= 0.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1, mOplusChangedConfigs= 0, OpSans= 4096, mFlag= 0"},"DISPLAY":{"0":{"currentSizeRange":{"smallest":[1080,921],"largest":[2294,2253]},"flags":"FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE","metrics":{"density":2.549999952316284,"densityDpi":408,"scaledDensity":"x2.55","widthPixels":1080,"heightPixels":2253,"xdpi":386.3659973144531,"ydpi":403.0570068359375},"realMetrics":{"density":2.549999952316284,"densityDpi":408,"scaledDensity":"x2.55","widthPixels":1080,"heightPixels":2412,"xdpi":386.3659973144531,"ydpi":403.0570068359375},"name":"Built-in Screen","realSize":[1080,2412],"rectSize":[0,0,1080,2253],"size":[1080,2253],"rotation":"ROTATION_0","isValid":true,"orientation":0,"refreshRate":90,"height":2253,"width":1080,"pixelFormat":1}},"USER_COMMENT":null,"USER_EMAIL":"N\/A","USER_APP_START_DATE":"2023-08-13T17:41:32.902+05:30","USER_CRASH_DATE":"2023-08-13T17:41:33.577+05:30","DUMPSYS_MEMINFO":"","LOGCAT":"08-13 17:41:33.141 D\/ScrollOptimizationHelper(17526): will not debug for debug is false\n08-13 17:41:33.141 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.141 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.141 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n--------- beginning of system\n08-13 17:41:33.164 E\/OplusCustomizeRestrictionManager(17526): sInstance is null, start a new sInstance\n08-13 17:41:33.167 D\/CompatibilityChangeReporter(17526): Compat change id reported: 210923482; UID 10459; state: ENABLED\n08-13 17:41:33.181 V\/TextView(17526): notifyAutoFillManagerAfterTextChanged\n08-13 17:41:33.181 V\/AutofillManager(17526): notifyValueChanged(1073741824): ignoring on state UNKNOWN\n08-13 17:41:33.184 V\/TextView(17526): notifyAutoFillManagerAfterTextChanged\n08-13 17:41:33.184 V\/AutofillManager(17526): notifyValueChanged(1073741824): ignoring on state UNKNOWN\n08-13 17:41:33.288 D\/CompatibilityChangeReporter(17526): Compat change id reported: 171228096; UID 10459; state: ENABLED\n08-13 17:41:33.288 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.288 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.288 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.294 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.294 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.294 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.296 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.296 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.296 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.299 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.299 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.299 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.300 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.300 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.300 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.312 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.312 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.312 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.314 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.314 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.314 I\/oplus.android.OplusFrameworkFactoryImpl(17526): get feature:IOplusDynamicVsyncFeature\n08-13 17:41:33.318 D\/Check (17526): 17\n08-13 17:41:33.319 D\/Date (17526): onCreateView: Sun Aug 13 17:41:33 GMT+05:30 2023\n08-13 17:41:33.333 W\/System.err(17526): SLF4J: Failed to load class \"org.slf4j.impl.StaticLoggerBinder\".\n08-13 17:41:33.333 W\/System.err(17526): SLF4J: Defaulting to no-operation (NOP) logger implementation\n08-13 17:41:33.333 W\/System.err(17526): SLF4J: See http:\/\/www.slf4j.org\/codes.html#StaticLoggerBinder for further details.\n08-13 17:41:33.339 D\/OplusInputMethodUtil(17526): init sDebug to false, init sDebugIme to false, init sAlwaysOn to false\n08-13 17:41:33.339 D\/OplusInputMethodUtil(17526): updateDebugToClass InputMethodManager.DEBUG = false\n08-13 17:41:33.339 D\/OplusInputMethodUtil(17526): updateDebugToClass ImeFocusController.DEBUG = false\n08-13 17:41:33.339 D\/OplusInputMethodUtil(17526): updateDebugToClass BaseInputConnection.DEBUG = false\n08-13 17:41:33.339 D\/OplusInputMethodUtil(17526): updateDebugToClass ImeFocusController.sDebugIme = false\n08-13 17:41:33.346 D\/WindowManager(17526): Add to mViews: DecorView@96131b4[MainActivity],pkg= com.maxrave.simpmusic\n08-13 17:41:33.349 D\/ExtensionsLoader(17526): createInstance(64bit) : createExtendedFactory\n08-13 17:41:33.352 D\/ExtensionsLoader(17526): Opened libhwuiextimpl.so\n08-13 17:41:33.352 D\/ExtensionsLoader(17526): createInstance(64bit) : createExtendedFactory\n08-13 17:41:33.352 D\/ExtensionsLoader(17526): Opened libSchedAssistExtImpl.so\n08-13 17:41:33.352 I\/OplusSlideAnimOptHelper(17526): checkListMode: is blacklist mode = true\n08-13 17:41:33.353 D\/OplusSlideAnimOptHelper(17526): com.maxrave.simpmusic scrollEffectOpt enable = true\n08-13 17:41:33.364 D\/InputEventReceiver(17526): Input log is disabled\n08-13 17:41:33.395 D\/Check Index inside Service(17526): null\n08-13 17:41:33.395 D\/Check Queue(17526): getRelated: []\n08-13 17:41:33.398 I\/Choreographer(17526): Skipped 43 frames! The application may be doing too much work on its main thread.\n08-13 17:41:33.398 I\/Quality (17526): Skipped: false 5 cost 62.10323 refreshRate 11104414 bit true processName com.maxrave.simpmusic\n08-13 17:41:33.435 D\/BufferQueueConsumer(17526): [](id:447600000000,api:0,p:-1,c:17526) connect: controlledByApp=false\n08-13 17:41:33.435 D\/ExtensionsLoader(17526): createInstance(64bit) : createExtendedFactory\n08-13 17:41:33.436 D\/ExtensionsLoader(17526): Opened libSchedAssistExtImpl.so\n08-13 17:41:33.437 V\/ZoomWindowDecorView(17526): setLastReportedMergedConfiguration mZoomDisplayHeight: 2412 getDecorView.157364660\n08-13 17:41:33.437 I\/AdrenoGLES-0(17526): QUALCOMM build : 3d24e2bbef, I3c0bc64a9d\n08-13 17:41:33.437 I\/AdrenoGLES-0(17526): Build Date : 11\/10\/21\n08-13 17:41:33.437 I\/AdrenoGLES-0(17526): OpenGL ES Shader Compiler Version: EV031.32.02.16\n08-13 17:41:33.437 I\/AdrenoGLES-0(17526): Local Branch : \n08-13 17:41:33.437 I\/AdrenoGLES-0(17526): Remote Branch : \n08-13 17:41:33.437 I\/AdrenoGLES-0(17526): Remote Branch : \n08-13 17:41:33.437 I\/AdrenoGLES-0(17526): Reconstruct Branch : \n08-13 17:41:33.437 I\/AdrenoGLES-0(17526): Build Config : S P 10.0.7 AArch64\n08-13 17:41:33.437 I\/AdrenoGLES-0(17526): Driver Path : \/vendor\/lib64\/egl\/libGLESv2_adreno.so\n08-13 17:41:33.443 I\/AdrenoGLES-0(17526): PFP: 0x016ee197, ME: 0x00000000\n08-13 17:41:33.446 D\/VRI[MainActivity](17526): registerCallbacksForSync syncBuffer=false\n08-13 17:41:33.464 D\/BufferQueueProducer(17526): [VRI[MainActivity]#0(BLAST Consumer)0](id:447600000000,api:1,p:17526,c:17526) connect: api=1 producerControlledByApp=true\n08-13 17:41:33.493 D\/TrafficStats(17526): tagSocket(139) with statsTag=0xffffffff, statsUid=-1\n08-13 17:41:33.493 D\/TrafficStats(17526): tagSocket(138) with statsTag=0xffffffff, statsUid=-1\n08-13 17:41:33.493 D\/TrafficStats(17526): tagSocket(148) with statsTag=0xffffffff, statsUid=-1\n08-13 17:41:33.497 D\/VRI[MainActivity](17526): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false\n08-13 17:41:33.499 W\/Parcel (17526): Expecting binder but got null!\n08-13 17:41:33.499 D\/VRI[MainActivity](17526): draw finished.\n08-13 17:41:33.507 E\/ACRA (17526): ACRA caught a IndexOutOfBoundsException for com.maxrave.simpmusic\n08-13 17:41:33.507 E\/ACRA (17526): java.lang.IndexOutOfBoundsException\n08-13 17:41:33.507 E\/ACRA (17526): \tat androidx.media3.common.Timeline$1.getWindow(Timeline.java:993)\n08-13 17:41:33.507 E\/ACRA (17526): \tat androidx.media3.common.Timeline.getWindow(Timeline.java:1114)\n08-13 17:41:33.507 E\/ACRA (17526): \tat androidx.media3.common.BasePlayer.getMediaItemAt(BasePlayer.java:369)\n08-13 17:41:33.507 E\/ACRA (17526): \tat com.maxrave.simpmusic.service.SimpleMediaServiceHandler.getMediaItemWithIndex(SimpleMediaServiceHandler.kt:52)\n08-13 17:41:33.507 E\/ACRA (17526): \tat com.maxrave.simpmusic.service.test.source.FetchQueue$onStartCommand$1$1.emit(FetchQueue.kt:50)\n08-13 17:41:33.507 E\/ACRA (17526): \tat com.maxrave.simpmusic.service.test.source.FetchQueue$onStartCommand$1$1.emit(FetchQueue.kt:46)\n08-13 17:41:33.507 E\/ACRA (17526): \tat kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)\n08-13 17:41:33.507 E\/ACRA (17526): \tat kotlinx.coroutines.flow.ReadonlyStateFlow.collect(Unknown Source:2)\n08-13 17:41:33.507 E\/ACRA (17526): \tat com.maxrave.simpmusic.service.test.source.FetchQueue$onStartCommand$1.invokeSuspend(FetchQueue.kt:46)\n08-13 17:41:33.507 E\/ACRA (17526): \tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n08-13 17:41:33.507 E\/ACRA (17526): \tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)\n08-13 17:41:33.507 E\/ACRA (17526): \tat android.os.Handler.handleCallback(Handler.java:942)\n08-13 17:41:33.507 E\/ACRA (17526): \tat android.os.Handler.dispatchMessage(Handler.java:99)\n08-13 17:41:33.507 E\/ACRA (17526): \tat android.os.Looper.loopOnce(Looper.java:240)\n08-13 17:41:33.507 E\/ACRA (17526): \tat android.os.Looper.loop(Looper.java:351)\n08-13 17:41:33.507 E\/ACRA (17526): \tat android.app.ActivityThread.main(ActivityThread.java:8381)\n08-13 17:41:33.507 E\/ACRA (17526): \tat java.lang.reflect.Method.invoke(Native Method)\n08-13 17:41:33.507 E\/ACRA (17526): \tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)\n08-13 17:41:33.507 E\/ACRA (17526): \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)\n08-13 17:41:33.507 E\/ACRA (17526): \tSuppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1161cc2, Dispatchers.Main]\n","INSTALLATION_ID":"37a3fa3f-fa76-4175-96fa-1f1ade66681b","DEVICE_FEATURES":{"com.oplus.software.children_space_google_play_exp":true,"android.hardware.sensor.proximity":true,"com.oplus.software.viewtalk_google_play":true,"com.google.android.feature.ASI_MINIMAL":true,"android.hardware.sensor.accelerometer":true,"android.software.controls":true,"android.hardware.faketouch":true,"com.google.android.feature.D2D_CABLE_MIGRATION_FEATURE":true,"android.hardware.usb.accessory":true,"android.hardware.telephony.cdma":true,"android.software.backup":true,"android.hardware.touchscreen":true,"android.hardware.touchscreen.multitouch":true,"oppo.common.support.curved.display":true,"android.software.print":true,"com.oplus.assistantscreen.google_play_exp":true,"android.software.activities_on_secondary_displays":true,"oplus.software.support_gp.type_phone":true,"oppo.ovs.smartmic.support":true,"android.software.voice_recognizers":true,"com.google.lens.feature.CAMERA_INTEGRATION":true,"android.software.picture_in_picture":true,"oplus.deviceowner.support":true,"android.hardware.fingerprint":true,"android.hardware.sensor.gyroscope":true,"android.hardware.audio.low_latency":true,"android.software.vulkan.deqp.level":true,"android.software.cant_save_state":true,"android.hardware.security.model.compatible":true,"android.hardware.opengles.aep":true,"android.hardware.bluetooth":true,"oplus.software.support_gp.region_export":true,"android.software.window_magnification":true,"android.hardware.camera.autofocus":true,"android.hardware.telephony.gsm":true,"android.hardware.telephony.ims":true,"android.software.incremental_delivery":true,"android.software.sip.voip":true,"oplus.secrecy.support":true,"android.hardware.usb.host":true,"android.hardware.audio.output":true,"android.software.verified_boot":true,"android.hardware.camera.flash":true,"android.hardware.camera.front":true,"android.hardware.se.omapi.uicc":true,"android.hardware.screen.portrait":true,"android.hardware.sensor.stepdetector":true,"android.software.home_screen":true,"android.hardware.microphone":true,"android.software.autofill":true,"android.software.securely_removes_users":true,"android.hardware.bluetooth_le":true,"android.hardware.sensor.compass":true,"android.hardware.touchscreen.multitouch.jazzhand":true,"android.software.app_widgets":true,"android.software.input_methods":true,"android.hardware.sensor.light":true,"oppo.breeno.three.words.support":true,"android.hardware.vulkan.version":true,"android.software.companion_device_setup":true,"android.software.device_admin":true,"com.google.android.feature.WELLBEING":true,"android.hardware.wifi.passpoint":true,"android.hardware.camera":true,"com.games.exp":true,"android.hardware.screen.landscape":true,"android.hardware.ram.normal":true,"com.games.oppo":true,"android.software.managed_users":true,"com.oplus.android.feature.PAI":true,"android.software.webview":true,"android.hardware.sensor.stepcounter":true,"android.hardware.camera.capability.manual_post_processing":true,"com.google.lens.feature.IMAGE_INTEGRATION":true,"android.hardware.camera.any":true,"android.hardware.camera.capability.raw":true,"android.hardware.vulkan.compute":true,"com.google.android.apps.dialer.call_recording_audio":true,"android.software.connectionservice":true,"android.hardware.touchscreen.multitouch.distinct":true,"android.hardware.location.network":true,"android.software.cts":true,"android.software.sip":true,"android.hardware.camera.capability.manual_sensor":true,"android.software.app_enumeration":true,"oplus.software.support_gp.brand_oppo":true,"com.google.android.apps.dialer.SUPPORTED":true,"oppo.qualcomm.gemini.support":true,"android.hardware.camera.level.full":true,"oppo.hw.manufacturer.qualcomm":true,"android.hardware.wifi.direct":true,"android.software.live_wallpaper":true,"android.software.ipsec_tunnels":true,"android.hardware.location.gps":true,"android.software.midi":true,"android.hardware.hardware_keystore":true,"android.hardware.wifi":true,"android.hardware.location":true,"android.hardware.vulkan.level":true,"com.google.android.feature.PREMIER_TIER":true,"oplus.software.audio.karaoke_v2.support":true,"android.software.secure_lock_screen":true,"android.hardware.biometrics.face":true,"oplus.software.support_gp.product_light":true,"android.hardware.telephony":true,"android.software.file_based_encryption":true,"glEsVersion":"3.2"},"ENVIRONMENT":{"getDataDirectory":"\/data","getDataSystemDirectory":"\/data\/system","getDownloadCacheDirectory":"\/data\/cache","getExternalStorageDirectory":"\/storage\/emulated\/0","getExternalStorageState":"mounted","getInternalMediaDirectories":"[\/system\/media, \/oem\/media, \/product\/media, \/system_ext\/media, \/my_product\/media, \/my_region\/media, \/my_carrier\/media, \/my_company\/media, \/my_bigball\/media, \/data\/theme\/ring, \/data\/theme\/audio, \/data\/theme\/applying, \/data\/oplus\/multimedia\/ringtones, \/data\/oplus\/multimedia\/notifications, \/data\/oplus\/multimedia\/ui, \/data\/oppo\/multimedia\/ringtones, \/data\/oppo\/multimedia\/notifications, \/data\/oppo\/multimedia\/ui]","getLegacyExternalStorageDirectory":"\/sdcard","getMyBigballDirectory":"\/my_bigball","getMyCarrierDirectory":"\/my_carrier","getMyCompanyDirectory":"\/my_company","getMyCountryDirectory":"\/my_region","getMyEngineeringDirectory":"\/my_engineering","getMyHeytapDirectory":"\/my_heytap","getMyOperatorDirectory":"\/my_carrier","getMyPreloadDirectory":"\/my_preload","getMyProductDirectory":"\/my_product","getMyRegionDirectory":"\/my_region","getMyStockDirectory":"\/my_stock","getOdmDirectory":"\/odm","getOemDirectory":"\/oem","getOplusCotaDirectory":"\/my_carrier","getOplusCustomDirectory":"\/my_custom","getOplusEngineerDirectory":"\/my_engineering","getOplusProductDirectory":"\/my_product","getOplusVersionDirectory":"\/my_version","getProductDirectory":"\/product","getProductServicesDirectory":"\/product_services","getReserveDirectory":"\/mnt\/vendor\/oplusreserve","getResourceDirectory":"\/my_carrier","getRootDirectory":"\/system","getStorageDirectory":"\/storage","getSystemExtDirectory":"\/system_ext","getVendorDirectory":"\/vendor","isExternalStorageEmulated":true,"isExternalStorageLegacy":false,"isExternalStorageManager":false,"isExternalStorageRemovable":false,"isOplusCotaDirectoryEmpty":false,"isOplusCustomDirectoryEmpty":true,"isWhiteListMcp":false},"SHARED_PREFERENCES":{"default":"empty"}}
```

**Comment by funkyblue** [comment]
App crashes straight away for me. Tried reinstalling. I've sent a few logs. Pure Android 13 on a Nokia NR20.

**Comment by n3rdcub** [comment]
Still unable to download certain songs. Latest one was Billie Elish Lovely. Immediately errors out it failed. Song will play though.

Playlists seem broken also? When adding to playlist the only option is Suggested.

**Comment by CrazyWolf13** [comment]
This should be fixed according to dev.
