### ISSUE TITLE
It displays an error report everytime I open the app

### ISSUE THREAD

**Issue by FaqatZubair1** [maxrave-dev/SimpMusic#302]
**Describe the bug**
Everytime I close the app and tgen open it again, it displays an error message 

**To Reproduce**
1. Open the app and play something 
2. Close the app and clear it from recents 
3. Open the app again
**Expected behavior**
App should open normally

**Screenshots**

**Log (Error Details)**
Build version: 0.2.0 
Current date: 2024-03-09 18:17:10 
Device: Motorola moto g34 5G 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:562)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	... 1 more
Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: Session rejected the connection request.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.maxrave.simpmusic.service.SimpleMediaService.onCreate$lambda$2(SimpleMediaService.kt:110)
	at com.maxrave.simpmusic.service.SimpleMediaService.$r8$lambda$aYQNUK0m9DwoO51tcNDQ3EQ5guk(Unknown Source:0)
	at com.maxrave.simpmusic.service.SimpleMediaService$$ExternalSyntheticLambda2.run(Unknown Source:2)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at androidx.media3.session.MediaControllerHolder.maybeSetException(MediaControllerHolder.java:67)
	at androidx.media3.session.MediaControllerHolder.onRejected(MediaControllerHolder.java:57)
	at androidx.media3.session.MediaController.release(MediaController.java:530)
	at androidx.media3.session.MediaControllerImplBase$$ExternalSyntheticLambda41.run(Unknown Source:2)
	at androidx.media3.common.util.Util.postOrRun(Util.java:761)
	at androidx.media3.session.MediaController.runOnApplicationLooper(MediaController.java:1940)
	at androidx.media3.session.MediaControllerStub.lambda$onDisconnected$1(MediaControllerStub.java:96)
	at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda4.run(Unknown Source:0)
	at androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$12(MediaControllerStub.java:310)
	at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda13.run(Unknown Source:4)
	at androidx.media3.common.util.Util.postOrRun(Util.java:761)
	at androidx.media3.session.MediaControllerStub.dispatchControllerTaskOnHandler(MediaControllerStub.java:302)
	at androidx.media3.session.MediaControllerStub.onDisconnected(MediaControllerStub.java:94)
	at androidx.media3.session.MediaSessionService$MediaSessionServiceStub.lambda$connect$0$androidx-media3-session-MediaSessionService$MediaSessionServiceStub(MediaSessionService.java:729)
	at androidx.media3.session.MediaSessionService$MediaSessionServiceStub$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Handler.java:1000)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:242)
	at android.os.Looper.loop(Looper.java:362)
	at android.app.ActivityThread.main(ActivityThread.java:8393)
	... 3 more
Caused by: java.lang.SecurityException: Session rejected the connection request.
	... 23 more

User actions: 
2024-03-09 18:17:04: MainActivity created
2024-03-09 18:17:04: MainActivity resumed

**Comment by maxrave-dev** [comment]
Please kill the app completely. I don't know but may be the system killed app
