### ISSUE TITLE
Repeated  Crash during playback  log in description 

### ISSUE THREAD

**Issue by 22marco77** [maxrave-dev/SimpMusic#318]
Build version: 0.2.0 
Current date: 2024-03-16 14:49:23 
Device: HUAWEI LYA-L29 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.IllegalArgumentException: Navigation action/destination com.maxrave.simpmusic:id/action_bottom_navigation_item_home_to_settingsFragment cannot be found from the current destination NavGraph(com.maxrave.simpmusic:id/nav_bottom_navigation) startDestination={Destination(com.maxrave.simpmusic:id/bottom_navigation_item_home) label=fragment_home class=com.maxrave.simpmusic.ui.fragment.home.HomeFragment}
	at androidx.navigation.NavController.navigate(NavController.kt:1691)
	at androidx.navigation.NavController.navigate(NavController.kt:1609)
	at androidx.navigation.NavController.navigate(NavController.kt:1591)
	at androidx.navigation.NavController.navigate(NavController.kt:1574)
	at com.maxrave.simpmusic.extension.AllExtKt.navigateSafe(AllExt.kt:680)
	at com.maxrave.simpmusic.extension.AllExtKt.navigateSafe$default(AllExt.kt:675)
	at com.maxrave.simpmusic.ui.fragment.home.HomeFragment.initView$lambda$10(HomeFragment.kt:711)
	at com.maxrave.simpmusic.ui.fragment.home.HomeFragment.$r8$lambda$GCpp4AsI1uoeKpUAEsqdgpkqITE(Unknown Source:0)
	at com.maxrave.simpmusic.ui.fragment.home.HomeFragment$$ExternalSyntheticLambda4.onMenuItemClick(Unknown Source:2)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:225)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:977)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:156)
	at android.view.View.performClick(View.java:7317)
	at android.view.View.performClickInternal(View.java:7291)
	at android.view.View.access$3600(View.java:838)
	at android.view.View$PerformClick.run(View.java:28247)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

User actions: 
2024-03-16 12:50:02: MainActivity created
2024-03-16 12:50:03: MainActivity resumed
2024-03-16 12:58:08: MainActivity paused
2024-03-16 13:01:12: MainActivity resumed
2024-03-16 13:02:28: MainActivity paused
2024-03-16 13:16:26: MainActivity resumed
2024-03-16 13:16:43: MainActivity paused
2024-03-16 13:21:35: MainActivity resumed
2024-03-16 13:21:44: MainActivity paused
2024-03-16 13:24:52: MainActivity resumed
2024-03-16 13:25:04: MainActivity paused
2024-03-16 14:02:52: MainActivity resumed
2024-03-16 14:03:12: MainActivity paused
2024-03-16 14:31:47: MainActivity resumed
2024-03-16 14:31:50: MainActivity paused
2024-03-16 14:32:26: MainActivity resumed
2024-03-16 14:32:27: MainActivity paused
2024-03-16 14:37:08: MainActivity resumed
2024-03-16 14:37:10: MainActivity paused
2024-03-16 14:38:18: MainActivity resumed
2024-03-16 14:38:40: MainActivity paused
2024-03-16 14:39:50: MainActivity resumed
2024-03-16 14:40:10: MainActivity paused
2024-03-16 14:44:27: MainActivity resumed
2024-03-16 14:46:51: MainActivity paused
2024-03-16 14:46:54: MainActivity resumed
2024-03-16 14:47:46: MainActivity paused
2024-03-16 14:48:03: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi, is this still an issue as of 0.2.19?

**Comment by 22marco77** [comment]
No, build 0.2.0
