### ISSUE TITLE
Bugs After logging in to Spotify. 

### ISSUE THREAD

**Issue by 22marco77** [maxrave-dev/SimpMusic#320]
After logging in to Spotify. The following error has occurred

Build version: 0.2.0 
Current date: 2024-03-22 06:40:26 
Device: HUAWEI LYA-L29 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.IllegalArgumentException: Navigation action/destination com.maxrave.simpmusic:id/action_bottom_navigation_item_home_to_settingsFragment cannot be found from the current destination NavGraph(com.maxrave.simpmusic:id/nav_bottom_navigation) startDestination={Destination(com.maxrave.simpmusic:id/bottom_navigation_item_home) label=fragment_home class=com.maxrave.simpmusic.ui.fragment.home.HomeFragment}
	at androidx.navigation.NavController.navigate(NavController.kt:1691)
	at androidx.navigation.NavController.navigate(NavController.kt:1609)
	at androidx.navigation.NavController.navigate(NavController.kt:1591)
	at androidx.navigation.NavController.navigate(NavController.kt:1574)
	at com.maxrave.simpmusic.extension.AllExtKt.navigateSafe(AllExt.kt:680)
	at com.maxrave.simpmusic.extension.AllExtKt.navigateSafe$default(AllExt.kt:675)
	at com.maxrave.simpmusic.ui.fragment.home.HomeFragment.initView$lambda$10(HomeFragment.kt:711)
	at com.maxrave.simpmusic.ui.fragment.home.HomeFragment.$r8$lambda$GCpp4AsI1uoeKpUAEsqdgpkqITE(Unknown Source:0)
	at com.maxrave.simpmusic.ui.fragment.home.HomeFragment$$ExternalSyntheticLambda4.onMenuItemClick(Unknown Source:2)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:225)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:977)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:156)
	at android.view.View.performClick(View.java:7317)
	at android.view.View.performClickInternal(View.java:7291)
	at android.view.View.access$3600(View.java:838)
	at android.view.View$PerformClick.run(View.java:28247)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

User actions: 
2024-03-22 06:37:30: MainActivity created
2024-03-22 06:37:31: MainActivity resumed
2024-03-22 06:39:45: MainActivity paused
2024-03-22 06:40:05: MainActivity resumed

.

**Comment by maxrave-dev** [comment]
Did you try to log in on other device

**Comment by CrazyWolf13** [comment]
Closed, due to no response.
