### ISSUE TITLE
Bug SimpMusic 0.2.1

### ISSUE THREAD

**Issue by petergithubuser** [maxrave-dev/SimpMusic#363]
Build version: 0.2.1 
Current date: 2024-05-01 13:07:13 
Device: Xiaomi M2010J19CG 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.NullPointerException
	at com.maxrave.simpmusic.ui.fragment.SearchFragment.onViewCreated$lambda$7(SearchFragment.kt:785)
	at com.maxrave.simpmusic.ui.fragment.SearchFragment.$r8$lambda$yw6DxmbkD_yLK8KCw4YuVWpbAtY(Unknown Source:0)
	at com.maxrave.simpmusic.ui.fragment.SearchFragment$$ExternalSyntheticLambda3.onCheckedChanged(D8$$SyntheticClass:0)
	at com.google.android.material.chip.ChipGroup$1.onCheckedStateChanged(ChipGroup.java:166)
	at com.google.android.material.internal.CheckableGroup.onCheckedStateChanged(CheckableGroup.java:184)
	at com.google.android.material.internal.CheckableGroup.access$300(CheckableGroup.java:43)
	at com.google.android.material.internal.CheckableGroup$1.onCheckedChanged(CheckableGroup.java:83)
	at com.google.android.material.internal.CheckableGroup$1.onCheckedChanged(CheckableGroup.java:79)
	at com.google.android.material.chip.Chip.lambda$new$0$com-google-android-material-chip-Chip(Chip.java:264)
	at com.google.android.material.chip.Chip$$ExternalSyntheticLambda0.onCheckedChanged(D8$$SyntheticClass:0)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:180)
	at com.google.android.material.chip.Chip.setChecked(Chip.java:727)
	at android.widget.CompoundButton.onRestoreInstanceState(CompoundButton.java:606)
	at android.view.View.dispatchRestoreInstanceState(View.java:20457)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3941)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3941)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3941)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3941)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3941)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3941)
	at android.view.View.restoreHierarchyState(View.java:20435)
	at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:698)
	at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:3176)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3161)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:619)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1934)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:891)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:797)
	at androidx.fragment.app.FragmentManager.handleOnBackPressed(FragmentManager.java:717)
	at androidx.fragment.app.FragmentManager$1.handleOnBackPressed(FragmentManager.java:447)
	at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.kt:276)
	at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:678)
	at android.app.Activity.onKeyUp(Activity.java:3714)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2847)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4043)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:120)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:138)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:380)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5797)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5646)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5132)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5185)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5151)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5291)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5159)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5348)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5132)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5185)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5151)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5159)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5132)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5185)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5151)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5324)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5500)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3072)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2615)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2606)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3049)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

User actions: 
2024-05-01 13:06:59: MainActivity created
2024-05-01 13:07:00: MainActivity resumed

**Comment by petergithubuser** [comment]
![Screenshot_2024-05-01-13-07-17-997_com maxrave simpmusic](https://github.com/maxrave-dev/SimpMusic/assets/159736884/99b3845d-3a78-4de6-93ef-cae9fe8e0e18)

**Comment by CrazyWolf13** [comment]
This should be fixed as of 0.2.20, please reply if you can reproduce there.
