### ISSUE TITLE
Crash Associated with Podcast

### ISSUE THREAD

**Issue by anxiouslelimo** [maxrave-dev/SimpMusic#377]
**Describe the bug**
Opened the podcast https://music.youtube.com/playlist?list=PLbxxYekfzaHtlApTVOlwJDQJsdatrgSBi. UI stuck. App not responding and crash.

**Log (Error Details)**
Build version: 0.2.1 
Current date: 2024-05-18 12:23:15 
Device: Samsung SM-M307F 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	... 1 more
Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: Session rejected the connection request.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:592)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:551)
	at com.maxrave.simpmusic.service.SimpleMediaService.onCreate$lambda$2(SimpleMediaService.kt:115)
	at com.maxrave.simpmusic.service.SimpleMediaService.$r8$lambda$cOlpJWG4tg4derbYStvKCUHMiD8(Unknown Source:0)
	at com.maxrave.simpmusic.service.SimpleMediaService$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:807)
	at androidx.media3.session.MediaControllerHolder.maybeSetException(MediaControllerHolder.java:67)
	at androidx.media3.session.MediaControllerHolder.onRejected(MediaControllerHolder.java:57)
	at androidx.media3.session.MediaController.release(MediaController.java:548)
	at androidx.media3.session.MediaControllerImplBase$$ExternalSyntheticLambda40.run(D8$$SyntheticClass:0)
	at androidx.media3.common.util.Util.postOrRun(Util.java:824)
	at androidx.media3.session.MediaController.runOnApplicationLooper(MediaController.java:1958)
	at androidx.media3.session.MediaControllerStub.lambda$onDisconnected$1(MediaControllerStub.java:105)
	at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda7.run(D8$$SyntheticClass:0)
	at androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$12(MediaControllerStub.java:349)
	at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda5.run(D8$$SyntheticClass:0)
	at androidx.media3.common.util.Util.postOrRun(Util.java:824)
	at androidx.media3.session.MediaControllerStub.dispatchControllerTaskOnHandler(MediaControllerStub.java:341)
	at androidx.media3.session.MediaControllerStub.onDisconnected(MediaControllerStub.java:103)
	at androidx.media3.session.MediaSessionService$MediaSessionServiceStub.lambda$connect$0$androidx-media3-session-MediaSessionService$MediaSessionServiceStub(MediaSessionService.java:729)
	at androidx.media3.session.MediaSessionService$MediaSessionServiceStub$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	... 3 more
Caused by: java.lang.SecurityException: Session rejected the connection request.
	... 22 more

User actions: 
2024-05-18 12:20:36: MainActivity created
2024-05-18 12:20:37: MainActivity resumed

**Comment by Bwangster12** [comment]
I'm experiencing this exact same thing... whenever I try to play a podcast (specifically tried Joe Rogan), either my device crashes or the SystemUI crashes.

**Comment by CrazyWolf13** [comment]
hi, please check with 0.2.20 again.

**Comment by CrazyWolf13** [comment]
Closed due to no reply, if still relevant, please reply.
