### ISSUE TITLE
Every time open: An unexpected error occurred

### ISSUE THREAD

**Issue by amribrahim1** [maxrave-dev/SimpMusic#389]
![صورة واتساب بتاريخ 1445-11-24 في 11 47 51_715c576a](https://github.com/maxrave-dev/SimpMusic/assets/8148579/377663f3-4799-453f-b7ab-ebc74933c222)

Error details:

```
Build version: 0.2.1 
Current date: 2024-06-01 11:48:56 
Device: Realme RMX3780 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	... 1 more
Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: Session rejected the connection request.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:592)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:551)
	at com.maxrave.simpmusic.service.SimpleMediaService.onCreate$lambda$2(SimpleMediaService.kt:115)
	at com.maxrave.simpmusic.service.SimpleMediaService.$r8$lambda$cOlpJWG4tg4derbYStvKCUHMiD8(Unknown Source:0)
	at com.maxrave.simpmusic.service.SimpleMediaService$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:807)
	at androidx.media3.session.MediaControllerHolder.maybeSetException(MediaControllerHolder.java:67)
	at androidx.media3.session.MediaControllerHolder.onRejected(MediaControllerHolder.java:57)
	at androidx.media3.session.MediaController.release(MediaController.java:548)
	at androidx.media3.session.MediaControllerImplBase$$ExternalSyntheticLambda40.run(D8$$SyntheticClass:0)
	at androidx.media3.common.util.Util.postOrRun(Util.java:824)
	at androidx.media3.session.MediaController.runOnApplicationLooper(MediaController.java:1958)
	at androidx.media3.session.MediaControllerStub.lambda$onDisconnected$1(MediaControllerStub.java:105)
	at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda7.run(D8$$SyntheticClass:0)
	at androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$12(MediaControllerStub.java:349)
	at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda5.run(D8$$SyntheticClass:0)
	at androidx.media3.common.util.Util.postOrRun(Util.java:824)
	at androidx.media3.session.MediaControllerStub.dispatchControllerTaskOnHandler(MediaControllerStub.java:341)
	at androidx.media3.session.MediaControllerStub.onDisconnected(MediaControllerStub.java:103)
	at androidx.media3.session.MediaSessionService$MediaSessionServiceStub.lambda$connect$0$androidx-media3-session-MediaSessionService$MediaSessionServiceStub(MediaSessionService.java:729)
	at androidx.media3.session.MediaSessionService$MediaSessionServiceStub$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	... 3 more
Caused by: java.lang.SecurityException: Session rejected the connection request.
	... 23 more

User actions: 
2024-06-01 11:46:53: MainActivity created
2024-06-01 11:46:53: MainActivity resumed
```

**Comment by maxrave-dev** [comment]
Did you try to Force stop and restart app?

**Comment by 9t8455qv** [comment]
Having the same issue here
![Screenshot_2024-06-03-10-47-15-89_b4450e33c7076f102e79bbedaff38911](https://github.com/maxrave-dev/SimpMusic/assets/109484556/2f156ddc-3a05-49e7-8dfd-9ecd76bc214c)

**Comment by amribrahim1** [comment]
I had to reinstall the app, Now it works.
