### ISSUE TITLE
play crash

### ISSUE THREAD

**Issue by valiantyan** [maxrave-dev/SimpMusic#397]
Build version: 0.2.1 
Current date: 2024-06-17 14:51:12 
Device: HONOR BVL-AN00 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at com.maxrave.simpmusic.ui.fragment.other.PodcastFragment.onViewCreated$lambda$3(PodcastFragment.kt:118)
	at com.maxrave.simpmusic.ui.fragment.other.PodcastFragment.$r8$lambda$pObGCE7HXl7Mli-jFbrwyeqSgp8(Unknown Source:0)
	at com.maxrave.simpmusic.ui.fragment.other.PodcastFragment$$ExternalSyntheticLambda3.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:8027)
	at android.view.View.performClickInternal(View.java:7996)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31986)
	at android.os.Handler.handleCallback(Handler.java:996)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:302)
	at android.app.ActivityThread.main(ActivityThread.java:9652)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)

User actions: 
2024-06-17 14:49:44: MainActivity created
2024-06-17 14:49:44: MainActivity resumed
2024-06-17 14:49:45: MainActivity paused
2024-06-17 14:49:45: MainActivity destroyed
2024-06-17 14:49:45: MainActivity created
2024-06-17 14:49:45: MainActivity resumed
2024-06-17 14:49:45: MainActivity paused
2024-06-17 14:49:47: MainActivity resumed
2024-06-17 14:49:55: MainActivity paused
2024-06-17 14:49:55: MainActivity destroyed
2024-06-17 14:49:55: MainActivity created
2024-06-17 14:49:56: MainActivity resumed
2024-06-17 14:50:37: MainActivity paused
2024-06-17 14:50:38: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi, is this still an issue as of 0.2.19?

**Comment by CrazyWolf13** [comment]
Closed, due to no reply and unable to recreate.<br>Please reply if not solved on latest (v0.2.21).
