### ISSUE TITLE
Restart the application

### ISSUE THREAD

**Issue by IkisIvy** [maxrave-dev/SimpMusic#422]
**Describe the bug**
Can't use the app

**To Reproduce**
1.Click on app.
2. The app reports an error and asks to restart.
3. Click restart but still have the same problem

**Screenshots**
![Screenshot_2024-06-30-21-36-04-32_b4450e33c7076f102e79bbedaff38911.jpg](https://github.com/maxrave-dev/SimpMusic/assets/157471349/d812d8fe-e721-4169-ad1e-dc810d8a899f)

**Log (Error Details)**
Build version: 0.2.2 
Current date: 2024-06-30 21:43:49 
Device: OPPO CPH2081 
OS version: Android 9 (SDK 28) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.maxrave.simpmusic/com.maxrave.simpmusic.ui.MainActivity}: java.lang.StringIndexOutOfBoundsException: length=0; index=2
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3191)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3328)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2054)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:7225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)
Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=2
	at java.lang.String.substring(String.java:2032)
	at kotlin.text.StringsKt__StringsKt.substring(Strings.kt:405)
	at com.maxrave.simpmusic.viewModel.SharedViewModel.getLocation(SharedViewModel.kt:1369)
	at com.maxrave.simpmusic.ui.MainActivity.onCreate(MainActivity.kt:449)
	at android.app.Activity.performCreate(Activity.java:7378)
	at android.app.Activity.performCreate(Activity.java:7369)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3171)
	... 11 more

User actions: 
2024-06-30 21:41:00: MainActivity created

**Comment by maxrave-dev** [comment]
Try to change per-app language

**Comment by machiavel23** [comment]
Build version: 0.2.2 
Current date: 2024-07-02 15:50:54 
Device: Motorola moto g fast 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.maxrave.simpmusic/com.maxrave.simpmusic.ui.MainActivity}: java.lang.StringIndexOutOfBoundsException: length=0; index=2
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3506)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3681)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2130)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7803)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=2
	at java.lang.String.substring(String.java:2060)
	at kotlin.text.StringsKt__StringsKt.substring(Strings.kt:405)
	at com.maxrave.simpmusic.viewModel.SharedViewModel.getLocation(SharedViewModel.kt:1369)
	at com.maxrave.simpmusic.ui.MainActivity.onCreate(MainActivity.kt:449)
	at android.app.Activity.performCreate(Activity.java:8104)
	at android.app.Activity.performCreate(Activity.java:8088)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3479)
	... 11 more

User actions: 
2024-07-02 15:50:47: MainActivity created
![Screenshot_20240702-155634](https://github.com/maxrave-dev/SimpMusic/assets/30846033/8c66778f-abfd-49bc-948a-c22306e41f6f)

**Comment by Logan7899** [comment]
![Screenshot_20240703-120612_Pixel Launcher](https://github.com/maxrave-dev/SimpMusic/assets/120176369/0dddb3b9-8ad2-417e-acef-7c1e89c265e8)
Me facing invisible controls

**Comment by maxrave-dev** [comment]
Did you try latest build?

**Comment by CrazyWolf13** [comment]
This problem was solved long ago, please check again with latest version.
