### ISSUE TITLE
Crash while opening the app SimpMusic 0.2.2

### ISSUE THREAD

**Issue by petergithubuser** [maxrave-dev/SimpMusic#437]
Build version: 0.2.2 
Current date: 2024-07-09 16:10:42 
Device: Xiaomi M2010J19CG 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.maxrave.simpmusic/com.maxrave.simpmusic.ui.MainActivity}: java.lang.StringIndexOutOfBoundsException: length=0; index=2
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3322)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3471)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:226)
	at android.app.ActivityThread.main(ActivityThread.java:7592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=2
	at java.lang.String.substring(String.java:2060)
	at kotlin.text.StringsKt__StringsKt.substring(Strings.kt:405)
	at com.maxrave.simpmusic.viewModel.SharedViewModel.getLocation(SharedViewModel.kt:1369)
	at com.maxrave.simpmusic.ui.MainActivity.onCreate(MainActivity.kt:449)
	at android.app.Activity.performCreate(Activity.java:7916)
	at android.app.Activity.performCreate(Activity.java:7903)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3297)
	... 11 more

User actions: 
2024-07-09 16:10:36: MainActivity created

**Comment by maxrave-dev** [comment]
Try to change per-app language in app settings
