### ISSUE TITLE
Ứng dụng không hoạt động 

### ISSUE THREAD

**Issue by datanh2596** [maxrave-dev/SimpMusic#445]
Build version: 0.2.2 
Current date: 2024-07-13 05:46:06 
Device: Xiaomi 23127PN0CC 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at com.maxrave.simpmusic.ui.fragment.other.AlbumFragment.onViewCreated$lambda$7(AlbumFragment.kt:333)
	at com.maxrave.simpmusic.ui.fragment.other.AlbumFragment.$r8$lambda$8G-ALajZY8W_mFq6CjLn3Ii-QpU(Unknown Source:0)
	at com.maxrave.simpmusic.ui.fragment.other.AlbumFragment$$ExternalSyntheticLambda4.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7797)
	at android.view.View.performClickInternal(View.java:7774)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31138)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8711)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

User actions: 
2024-07-13 05:36:19: MainActivity created
2024-07-13 05:36:20: MainActivity resumed

**Comment by maxrave-dev** [comment]
Bạn mở ứng dụng lên thì bị lỗi hay sao ạ?

**Comment by maxrave-dev** [comment]
Bạn đang mở Album rỗng?

**Comment by CrazyWolf13** [comment]
Hi @datanh2596  is this issue still appearing with 0.2.19?

**Comment by CrazyWolf13** [comment]
Closed, due to no reply and unable to recreate.<br>Please reply if not solved on latest (v0.2.21).
