### ISSUE TITLE
SimpMusic Debug Error Version 2.3

### ISSUE THREAD

**Issue by Khaerl-dev** [maxrave-dev/SimpMusic#474]
**Describe the bug**
i just downloaded the Nightly Version bcs i wanna try the new feature, i already logged everything went smoothly until i close the app to rest and try to open the app again, I can't .
**To Reproduce**
1. Open The App
2. See error

**Expected behavior**
Normal Home screen 

**Screenshots**

**Log (Error Details)**

Build version: 0.2.3-dev 
Current date: 2024-08-08 11:27:07 
Device: Xiaomi M2101K6G 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.NoSuchMethodError: No interface method removeLast()Ljava/lang/Object; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /apex/com.android.art/javalib/core-oj.jar)
	at com.maxrave.simpmusic.data.parser.HomeParserKt.parseNewRelease(HomeParser.kt:715)
	at com.maxrave.simpmusic.data.repository.MainRepository$getNewRelease$2.invokeSuspend(MainRepository.kt:657)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@46cef86, Dispatchers.Main.immediate]

User actions: 
2024-08-08 11:26:58: MainActivity created
2024-08-08 11:27:00: MainActivity resumed
![IMG_20240808_111621](https://github.com/user-attachments/assets/57c6115d-33ed-44d1-9a28-44ef283d3090)

**Comment by maxrave-dev** [comment]
#472
