### ISSUE TITLE
0.2.3-hotfix crashes when starting

### ISSUE THREAD

**Issue by just-Nob** [maxrave-dev/SimpMusic#492]
**Bug Description**
When starting version 0.2.3-hotfix, it immediately crashes.

**To Reproduce**
Start app.

**Expected behavior**
App doesn't crash.

**Device**
Poco X3 NFC
ArrowOS 11.0 VANILLA build + microG + Magisk

**Log (Error Details)**
Build version: 0.2.3-hotfix 
Current date: 2024-08-12 21:53:20 
Device: Unknown 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.maxrave.simpmusic/com.maxrave.simpmusic.ui.MainActivity}: java.lang.StringIndexOutOfBoundsException: length=0; index=2
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=2
	at java.lang.String.substring(String.java:2060)
	at La.G.substring(SourceFile:1)
	at com.maxrave.simpmusic.viewModel.SharedViewModel.getLocation(Unknown Source:59)
	at com.maxrave.simpmusic.ui.MainActivity.onCreate(Unknown Source:683)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
	... 11 more

User actions: 
2024-08-12 21:52:45: MainActivity created

**Comment by maxrave-dev** [comment]
Change language in app settings

**Comment by just-Nob** [comment]
Not possible without deinstalling, since app's crashing IMMEDIATELY...

**Comment by maxrave-dev** [comment]
https://support.google.com/android/answer/12395118?hl=en follow this

**Comment by just-Nob** [comment]
Deleting all settings works, but for sure this is equivalent to a fresh Installation.

**Comment by just-Nob** [comment]
> https://support.google.com/android/answer/12395118?hl=en follow this

Thanks a lot - it looks like I was too fast. 😇
Anyway, I just lost my history, that's OK.
But maybe your hint is helpful for others having the same problem!

**Comment by maxrave-dev** [comment]
What is your device default language?

**Comment by just-Nob** [comment]
Sorry for the delayed reply.

My default language is German.

However, I'm not sure if I had switched it to English for some reason sometime before.
I'm going that sometimes for reducing translation errors, or when I like to describe some app's behavior on Github.
