### ISSUE TITLE
Automatic force close after opening app (on latest version)

### ISSUE THREAD

**Issue by LHLXD** [maxrave-dev/SimpMusic#500]
Updated to the latest version with hot fix and upon opening, I got a pop up trying to tell me to update the latest version even though I did do it manually from the GitHub page, then it changed and popped up saying an error has occured and showed me the error code, and then kicked me out and closed the app.
Here is the error code if that helps you:
Build version: 0.2.3-hotfix 
Current date: 2024-08-14 00:26:50 
Device: Google Pixel 6 Pro 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at a7.L0.updateCatalog(Unknown Source:529)
	at a7.L0.load(Unknown Source:62)
	at a7.L0.load$default(Unknown Source:10)
	at a7.l0.invokeSuspend(Unknown Source:36)
	at j9.a.resumeWith(Unknown Source:11)
	at Na.f0.run(Unknown Source:130)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: Ta.j: [o1{Cancelling}@644f095, Dispatchers.Main]

User actions: 
2024-08-14 00:26:30: MainActivity created
2024-08-14 00:26:31: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi @LHLXD,
Is this still an issue as of version 2.19?

**Comment by CrazyWolf13** [comment]
Closed, due to no reply and unable to recreate.<br>Please reply if not solved on latest (v0.2.21).
