### ISSUE TITLE
Unexpected Error occured after pressing the like (heart) of an Album which forces an App restart.

### ISSUE THREAD

**Issue by laurenz0071** [maxrave-dev/SimpMusic#501]
**Describe the bug**
Unexpected Error occured after pressing the like (heart) of an Album which forces an App restart.

**To Reproduce**

**Expected behavior**
That the Album just get liked without the unexpected error which required an app restart.

**Screenshots**

**Log (Error Details)**
Build version: 0.2.3-hotfix 
Current date: 2024-08-14 08:20:00 
Device: Google Pixel 8 Pro 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.NullPointerException
	at com.maxrave.simpmusic.ui.fragment.other.AlbumFragment.access$getBinding(Unknown Source:2)
	at l7.g.emit(SourceFile:2)
	at l7.g.emit(SourceFile:1)
	at Qa.o1.collect(Unknown Source:184)
	at Qa.n1.invokeSuspend(Unknown Source:12)
	at j9.a.resumeWith(Unknown Source:11)
	at Na.g0.resume(Unknown Source:61)
	at Na.g0.dispatch(Unknown Source:71)
	at Na.o.b(Unknown Source:13)
	at Na.o.g(Unknown Source:33)
	at Na.o.resumeWith(Unknown Source:7)
	at Qa.q1.makePending(Unknown Source:60)
	at Qa.o1.a(Unknown Source:58)
	at Qa.o1.setValue(Unknown Source:5)
	at u7.T.emit(SourceFile:3)
	at u7.T.emit(SourceFile:1)
	at Qa.x.a(Unknown Source:133)
	at Qa.x.access$emitAllImpl$FlowKt__ChannelsKt(Unknown Source:0)
	at Qa.w.invokeSuspend(Unknown Source:11)
	at j9.a.resumeWith(Unknown Source:11)
	at Na.f0.run(Unknown Source:130)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: Ta.j: [o1{Cancelling}@8595eb6, Dispatchers.Main.immediate]

User actions: 
2024-08-14 08:17:26: MainActivity created
2024-08-14 08:17:26: MainActivity resumed
2024-08-14 08:17:26: MainActivity paused
2024-08-14 08:17:26: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi,<br>Does this still happen with 0.2.19?

**Comment by laurenz0071** [comment]
Right now I use v.0.2.20 where this problem seems to be solved. Thanks

**Comment by CrazyWolf13** [comment]
Awesome :)
