### ISSUE TITLE
App crashing on pixel 6

### ISSUE THREAD

**Issue by nickvanced** [maxrave-dev/SimpMusic#517]
**Describe the bug**
App does not load and gives an error message on pixel 6 since 31st August, 2024.

**To Reproduce**
1. Open the app

**Screenshots**
![Screenshot_20240902-222024.png](https://github.com/user-attachments/assets/eb41d661-2757-4f18-895f-6bb3f7e7d7d7)

**Log (Error Details)**
Error details : 
Build version: 0.2.3-hotfix 
Current date: 2024-09-02 22:18:55 
Device: Google Pixel 6 
OS version: Android 15 (SDK 35) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at a7.L0.updateCatalog(Unknown Source:529)
	at a7.L0.load(Unknown Source:62)
	at a7.L0.load$default(Unknown Source:10)
	at a7.l0.invokeSuspend(Unknown Source:36)
	at j9.a.resumeWith(Unknown Source:11)
	at Na.f0.run(Unknown Source:130)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8700)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
	Suppressed: Ta.j: [o1{Cancelling}@a2c548b, Dispatchers.Main]

User actions: 
2024-09-02 22:18:51: MainActivity created
2024-09-02 22:18:52: MainActivity resumed

**Comment by abdulisik** [comment]
Similar crash on Samsung. See below.
Build version: 0.2.3-hotfix 
Current date: 2024-09-13 16:07:59 
Device: Samsung SM-S908U1 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at a7.L0.updateCatalog(Unknown Source:529)
	at a7.L0.load(Unknown Source:62)
	at a7.L0.load$default(Unknown Source:10)
	at a7.l0.invokeSuspend(Unknown Source:36)
	at j9.a.resumeWith(Unknown Source:11)
	at Na.f0.run(Unknown Source:130)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: Ta.j: [o1{Cancelling}@442ad16, Dispatchers.Main]

User actions: 
2024-09-13 16:07:42: MainActivity created
2024-09-13 16:07:43: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi, can you all check with 0.2.19?<br>This should be already fixed.

**Comment by CrazyWolf13** [comment]
Closed, due to no reply and unable to recreate.<br>Please reply if not solved on latest (v0.2.21).
