### ISSUE TITLE
Holy moly 

### ISSUE THREAD

**Issue by Zdertis420** [maxrave-dev/SimpMusic#520]
Here's the log, idfk how reproduce this bug

Build version: 0.2.3-hotfix 
Current date: 2024-09-15 01:38:26 
Device: Samsung SM-S928B 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.NullPointerException
	at l7.q1.invokeSuspend(Unknown Source:417)
	at l7.q1.invoke(SourceFile:1)
	at l7.q1.invoke(SourceFile:2)
	at Qa.b0.invokeSuspend(Unknown Source:45)
	at Qa.b0.invoke(SourceFile:1)
	at Qa.b0.invoke(SourceFile:2)
	at Ra.l.invokeSuspend(Unknown Source:38)
	at Ra.l.invoke(SourceFile:1)
	at Ra.l.invoke(SourceFile:2)
	at Ua.b.startCoroutineUndispatched(Unknown Source:31)
	at Na.U.invoke(Unknown Source:15)
	at Na.a.start(Unknown Source:0)
	at Na.i.launch(Unknown Source:22)
	at Na.g.launch(Unknown Source:0)
	at Na.i.launch$default(Unknown Source:12)
	at Na.g.launch$default(Unknown Source:0)
	at Ra.n.emit(Unknown Source:108)
	at Qa.L0.invokeSuspend(Unknown Source:62)
	at Qa.L0.invoke(SourceFile:1)
	at Qa.L0.invoke(SourceFile:2)
	at Ra.w.invokeSuspend(Unknown Source:284)
	at j9.a.resumeWith(Unknown Source:11)
	at Na.f0.run(Unknown Source:130)
	at Na.n0.processUnconfinedEvent(Unknown Source:15)
	at Ta.l.resumeCancellableWith(Unknown Source:142)
	at Ua.a.startCoroutineCancellable(SourceFile:1)
	at Ua.a.startCoroutineCancellable$default(Unknown Source:5)
	at Na.U.invoke(Unknown Source:35)
	at Na.a.start(Unknown Source:0)
	at Na.i.launch(Unknown Source:22)
	at Na.g.launch(Unknown Source:0)
	at Na.i.launch$default(Unknown Source:12)
	at Na.g.launch$default(Unknown Source:0)
	at androidx.lifecycle.i0.onStateChanged(Unknown Source:32)
	at androidx.lifecycle.H.dispatchEvent(Unknown Source:24)
	at androidx.lifecycle.I.d(Unknown Source:349)
	at androidx.lifecycle.I.c(Unknown Source:76)
	at androidx.lifecycle.I.handleLifecycleEvent(Unknown Source:14)
	at Z1.F0.q(Unknown Source:56)
	at Z1.F0.k(Unknown Source:71)
	at Z1.v0.B(Unknown Source:1158)
	at Z1.v0.P(Unknown Source:91)
	at Z1.v0.M(Unknown Source:45)
	at Z1.v0.popBackStackImmediate(Unknown Source:2)
	at Z1.e0.handleOnBackPressed(Unknown Source:259)
	at d.Q.onBackPressed(Unknown Source:43)
	at d.s.onBackPressed(Unknown Source:4)
	at android.app.Activity.onKeyUp(Activity.java:4157)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3522)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4505)
	at p1.q.superDispatchKeyEvent(Unknown Source:5)
	at B1.x.dispatchKeyEvent(Unknown Source:10)
	at p1.q.dispatchKeyEvent(Unknown Source:26)
	at k.o.dispatchKeyEvent(Unknown Source:22)
	at p.q.dispatchKeyEvent(Unknown Source:2)
	at k.H.dispatchKeyEvent(Unknown Source:21)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:684)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:8485)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8345)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7678)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7735)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7701)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7904)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7709)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7961)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7682)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7735)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7701)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7709)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7682)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7735)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7701)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7937)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:8179)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:4578)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:4012)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:4003)
	at android.view.inputmethod.InputMethodManager.-$$Nest$mfinishedInputEvent(Unknown Source:0)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:4555)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:187)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: Ta.j: [o1{Cancelling}@701c186, Dispatchers.Main.immediate]

User actions: 
2024-09-15 01:37:53: MainActivity created
2024-09-15 01:37:54: MainActivity resumed

**Comment by Iliano101** [comment]
That seems quite similar to the issues I got (#485)

**Comment by CrazyWolf13** [comment]
Duplicate and should be resolved long ago.
