### ISSUE TITLE
App crashes when adding to playlist

### ISSUE THREAD

**Issue by anii-chan** [maxrave-dev/SimpMusic#537]
**Describe the bug**
The app crashes when adding a song to a playlist. Usually doesn't happen with the first song played but almost always happens once you're a few songs in. Sometimes song will still add to playlist but app still crashes.

**To Reproduce**
1. Play 'quick picks radio' or some other playlist/radio.
2. Click 'add to a playlist' after a few songs in
3. Select playlist

**Expected behavior**
Expected to add to playlist without error.

**Screenshots**
![an unexpected error has occurred. sorry for the inconvenience](https://files.catbox.moe/jd62it.jpg)

**Log (Error Details)**
Build version: 0.2.3-hf2-dev 
Current date: 2024-10-24 11:18:13 
Device: Samsung SM-S901U 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY[787])
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:1294)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.kt:42)
	at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.kt:51)
	at com.maxrave.simpmusic.data.db.DatabaseDao_Impl$59.call(DatabaseDao_Impl.java:1292)
	at com.maxrave.simpmusic.data.db.DatabaseDao_Impl$59.call(DatabaseDao_Impl.java:1286)
	at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.kt:36)
	at androidx.room.TransactionExecutor.$r8$lambda$FZWr2PGmP3sgXLCiri-DCcePXSs(Unknown Source:0)
	at androidx.room.TransactionExecutor$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@de7144a, Dispatchers.Main.immediate]

User actions: 
2024-10-24 11:14:57: MainActivity created
2024-10-24 11:14:58: MainActivity resumed
2024-10-24 11:15:04: MainActivity paused
2024-10-24 11:17:20: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi, can you check with version 0.2.19?

**Comment by CrazyWolf13** [comment]
Closed, due to no reply and unable to recreate.<br>Please reply if not solved on latest (v0.2.21).
