### ISSUE TITLE
Unexpected Error upon opening an Album. Restart of the App necessary.

### ISSUE THREAD

**Issue by laurenz0071** [maxrave-dev/SimpMusic#544]
**Describe the bug**
Go to a Band, click on their Album tabs, click on an Album, instead of the Album opening to play songs, "an unexpected Error occurred" and I had to restart the app.

**To Reproduce**
1. Go to 'an Artists Page'
2. Click on 'Albums and an Album'
3. See error

**Expected behavior**
An Album should open without "unexpected Error occurred" and therefore I should be able to olay music and nit need to restart tge App.

**Log (Error Details)**
Build version: 0.2.3-hotfix 
Current date: 2024-10-25 13:12:29 
Device: Google Pixel 8 Pro 
OS version: Android 15 (SDK 35) 
 
Stack trace:  
java.lang.NullPointerException
	at com.maxrave.simpmusic.ui.fragment.other.AlbumFragment.access$getBinding(Unknown Source:2)
	at l7.g.emit(SourceFile:2)
	at l7.g.emit(SourceFile:1)
	at Qa.o1.collect(Unknown Source:184)
	at Qa.n1.invokeSuspend(Unknown Source:12)
	at j9.a.resumeWith(Unknown Source:11)
	at Na.g0.resume(Unknown Source:61)
	at Na.g0.dispatch(Unknown Source:71)
	at Na.o.b(Unknown Source:13)
	at Na.o.g(Unknown Source:33)
	at Na.o.resumeWith(Unknown Source:7)
	at Qa.q1.makePending(Unknown Source:60)
	at Qa.o1.a(Unknown Source:58)
	at Qa.o1.setValue(Unknown Source:5)
	at u7.K.emit(SourceFile:2)
	at u7.K.emit(SourceFile:12)
	at Qa.x.a(Unknown Source:133)
	at Qa.x.access$emitAllImpl$FlowKt__ChannelsKt(Unknown Source:0)
	at Qa.w.invokeSuspend(Unknown Source:11)
	at j9.a.resumeWith(Unknown Source:11)
	at Na.f0.run(Unknown Source:130)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: Ta.j: [o1{Cancelling}@b8acd6c, Dispatchers.Main.immediate]

User actions: 
2024-10-25 13:11:28: MainActivity created
2024-10-25 13:11:28: MainActivity resumed
2024-10-25 13:11:28: MainActivity paused
2024-10-25 13:11:28: MainActivity resumed

**Comment by laurenz0071** [comment]
This problem seems to be solved. (v0.2.20)

**Comment by CrazyWolf13** [comment]
thanks for the reply :)
