### ISSUE TITLE
Fix error Error inesperado

### ISSUE THREAD

**Issue by marco7722** [maxrave-dev/SimpMusic#550]
Build version: 0.2.3-hotfix 
Current date: 2024-10-31 22:49:50 
Device: HUAWEI LYA-L29 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at a7.L0.updateCatalog(Unknown Source:529)
	at a7.L0.load(Unknown Source:62)
	at a7.L0.load$default(Unknown Source:10)
	at a7.l0.invokeSuspend(Unknown Source:36)
	at j9.a.resumeWith(Unknown Source:11)
	at Na.f0.run(Unknown Source:130)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
	Suppressed: Ta.j: [o1{Cancelling}@7d78d66, Dispatchers.Main]

User actions: 
2024-10-31 22:49:46: MainActivity created
2024-10-31 22:49:46: MainActivity resumed

**Comment by CrazyWolf13** [comment]
This issues has been resolved, please reply if not.
