### ISSUE TITLE
App crashes when oppening

### ISSUE THREAD

**Issue by madbxd** [maxrave-dev/SimpMusic#557]
Crashes when open in the new version 0.2.4

1. Open simpMusic
2. Crashes instantly

**Screenshots**
![Screenshot_20241110-090742](https://github.com/user-attachments/assets/318f3a79-7c4a-4431-a075-c292793d7b9f)

Translation : an error occured, we're sorry for the annoyance that happened. 

**Log (Error Details)**
Build version: 0.2.4 
Current date: 2024-11-10 09:05:31 
Device: Google Pixel 7 
OS version: Android 15 (SDK 35) 
 
Stack trace:  
java.lang.IllegalArgumentException: class i6.b isn't parameterized
	at d6.o.checkArgument(SourceFile:4)
	at i6.b.<init>(Unknown Source:15)
	at k7.d.migrate(Unknown Source:38)
	at b4.h0.onUpgrade(Unknown Source:38)
	at g4.k.onUpgrade(Unknown Source:14)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:415)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at g4.k.a(Unknown Source:4)
	at g4.k.b(Unknown Source:63)
	at g4.k.getSupportDatabase(Unknown Source:23)
	at g4.m.getWritableDatabase(Unknown Source:9)
	at b4.Y.inTransaction(Unknown Source:4)
	at b4.Y.assertNotSuspendingTransaction(Unknown Source:0)
	at b4.Y.query(Unknown Source:8)
	at d4.b.query(Unknown Source:10)
	at c7.k.call(SourceFile:2)
	at c7.k.call(SourceFile:1)
	at b4.d.invokeSuspend(Unknown Source:86)
	at m9.a.resumeWith(Unknown Source:11)
	at Qa.f0.run(Unknown Source:130)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: Wa.j: [p1{Cancelling}@27aa98e, Dispatchers.Main.immediate]

User actions: 
2024-11-10 09:05:23: MainActivity created
2024-11-10 09:05:23: MainActivity resumed

**Comment by maxrave-dev** [comment]
Try to delete app data, does it work again?

**Comment by madbxd** [comment]
> Try to delete app data, does it work again?

I wanted to in the first place but since i have so much stuff saved i cant do a backup data since the app doesnt wanna lunch. All my playlists favs etc will be gone if i do delete it 😞 and theyre local playlists so yea, i had a similar bug when 0.2.3 came out but the dev put a new version w a fix or something and it worked since then. Now the bug came back

**Comment by madbxd** [comment]
I have a solution, do a different version kinda like the same hotline fix on version 0.2.3 and we all gonna be alright :3

**Comment by CrazyWolf13** [comment]
@maxrave-dev I have the same problem :/

**Comment by madbxd** [comment]
> @maxrave-dev I have the same problem :/

Idk why these updates are breaking the app :( i love using simpmusic and i didnt wanna use youtube music or Spotify bc this specific ui is the best. Hope they fix this permanently

**Comment by CrazyWolf13** [comment]
This has been solved as of 0.2.20, and has not appeared since for me.
