### ISSUE TITLE
i cant restore my data after update to 0.2.4 all my saved songs are gone
anyone help T_T



### ISSUE THREAD

**Issue by viperhehe-max** [maxrave-dev/SimpMusic#558]
Build version: 0.2.4 
Current date: 2024-11-10 20:37:57 
Device: Vivo V2352A 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IllegalArgumentException: class i6.b isn't parameterized
	at d6.o.checkArgument(SourceFile:4)
	at i6.b.<init>(Unknown Source:15)
	at k7.d.migrate(Unknown Source:38)
	at b4.h0.onUpgrade(Unknown Source:38)
	at g4.k.onUpgrade(Unknown Source:14)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at g4.k.a(Unknown Source:4)
	at g4.k.b(Unknown Source:63)
	at g4.k.getSupportDatabase(Unknown Source:23)
	at g4.m.getWritableDatabase(Unknown Source:9)
	at b4.Y.inTransaction(Unknown Source:4)
	at b4.Y.assertNotSuspendingTransaction(Unknown Source:0)
	at b4.Y.query(Unknown Source:8)
	at d4.b.query(Unknown Source:10)
	at c7.k.call(SourceFile:2)
	at c7.k.call(SourceFile:1)
	at b4.d.invokeSuspend(Unknown Source:86)
	at m9.a.resumeWith(Unknown Source:11)
	at Qa.f0.run(Unknown Source:130)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1042)
	Suppressed: Wa.j: [p1{Cancelling}@22505fb, Dispatchers.Main.immediate]

User actions: 
2024-11-10 20:37:46: MainActivity created
2024-11-10 20:37:47: MainActivity resumed

**Comment by madbxd** [comment]
I have the same issue 😞 i didnt delete the app bc ik that would remove all my data

**Comment by maxrave-dev** [comment]
Which version you created the backup? In latest, I still restore okay and I can't re-appear this error

**Comment by madbxd** [comment]
> Which version you created the backup? In latest, I still restore okay and I can't re-appear this error



> I got that with like 3 last updates, and the fix was to clear all data of the app. If it didint help you should delete the app and then use latest version installer.
> 
> I gues that there are some conflicts with each new updates with old app data which makes it crash when launching.
> 
> P.s: I`ve lost downloaded tracks 3 updates ago and there is nothing to lose when I reinstall it like this, since all playlist remaining are the youtube account onesXD That is definetly not the desired way to get updates though...

I use local playlists so if i removed the app data, theyre truly gone

**Comment by madbxd** [comment]
> > Which version you created the backup? In latest, I still restore okay and I can't re-appear this error
> 
> Just tested and I had this error until I`ve cleared my data from the prev verison. Clearing cache does nothing with it, but clearing all data without reinstallation fixes it, so it must be issue with youtube account data or downloaded playlists or smth.
> 
> Imho to recreate it you can try to install previous version, logging in and downloading some playlists. I`ve also had sponsorblock, sending listening history to google and saving last played track enabled.
> 
> My total data size was 2GB, maybe this also matters

I had 3gb, i do use youtube playlists too but i also have a lot of local ones that i dont wanna lose :( the only thing ik is to rollback update to an older version but since google doesnt let u do that anymore im stuck w spotify which i hate using since of ads and to play in order u have to pay premium ughh

**Comment by viperhehe-max** [comment]
> Which version you created the backup? In latest, I still restore okay and I can't re-appear this error

0.2.3 hf2 its the version i used when i started using this app

**Comment by viperhehe-max** [comment]
> Which version you created the backup? In latest, I still restore okay and I can't re-appear this error

0.2.3 hf2 its the version i used when i started using this app

**Comment by maxrave-dev** [comment]
Can you try to use the nightly version to  restore your data, then backup in nightly version, finally, use the latest version to restore the file that backed up in nightly version

**Comment by madbxd** [comment]
> Can you try to use the nightly version to restore your data, then backup in nightly version, finally, use the latest version to restore the file that backed up in nightly version

Quite genius i will try

**Comment by maxrave-dev** [comment]
Check out Readme

**Comment by programmer584** [comment]
Same problem here. I installed the nightly version, but it doesn't seem to have access to the data of the normal version of SimpMusic.
I also tried installing the older apk's, but it seems android doesn't want me to downgrade. I namely got the error “App not installed as package turns out to be invalid”. 
Now I have two apps:
- The latest version, which normally contains all my songs and playlists. This one gives instant error on startup.
- The nightly version. This one seems to be just a fresh install of SimpMusic, with no data.

Is there any way to at least restore the downloaded songs? Thanks in advance for everyone's help. :)

**Comment by maxrave-dev** [comment]
Try the nightly version, it had an issue before

**Comment by chrisdebian** [comment]
Is this still a problem?

**Comment by CrazyWolf13** [comment]
Hi,<br>Does anyone still have this problem with the latest v0.2.19?

**Comment by CrazyWolf13** [comment]
Closed, due to no reply and unable to recreate.<br>Please reply if not solved on latest (v0.2.21).
