### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by x64x2** [maxrave-dev/SimpMusic#569]
Build version: 0.2.3-hotfix 
Current date: 2024-11-17 15:37:24 
Device: Samsung A39
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.NullPointerException
	at com.maxrave.simpmusic.ui.fragment.other.ArtistFragment.access$getBinding(Unknown Source:2)
	at l7.k0.invokeSuspend(Unknown Source:29)
	at l7.k0.invoke(SourceFile:2)
	at l7.k0.invoke(SourceFile:1)
	at Qa.b0.invokeSuspend(Unknown Source:45)
	at Qa.b0.invoke(SourceFile:1)
	at Qa.b0.invoke(SourceFile:2)
	at Ra.l.invokeSuspend(Unknown Source:38)
	at Ra.l.invoke(SourceFile:1)
	at Ra.l.invoke(SourceFile:2)
	at Ua.b.startCoroutineUndispatched(Unknown Source:31)
	at Na.U.invoke(Unknown Source:15)
	at Na.a.start(Unknown Source:0)
	at Na.i.launch(Unknown Source:22)
	at Na.g.launch(Unknown Source:0)
	at Na.i.launch$default(Unknown Source:12)
	at Na.g.launch$default(Unknown Source:0)
	at Ra.n.emit(Unknown Source:108)
	at Qa.o1.collect(Unknown Source:184)
	at Qa.n1.invokeSuspend(Unknown Source:12)
	at j9.a.resumeWith(Unknown Source:11)
	at Na.g0.resume(Unknown Source:61)
	at Na.g0.dispatch(Unknown Source:71)
	at Na.o.b(Unknown Source:13)
	at Na.o.g(Unknown Source:33)
	at Na.o.resumeWith(Unknown Source:7)
	at Qa.q1.makePending(Unknown Source:60)
	at Qa.o1.a(Unknown Source:58)
	at Qa.o1.setValue(Unknown Source:5)
	at Qa.o1.emit(Unknown Source:0)
	at u7.n0.emit(SourceFile:2)
	at u7.n0.emit(SourceFile:1)
	at Qa.x.a(Unknown Source:133)
	at Qa.x.access$emitAllImpl$FlowKt__ChannelsKt(Unknown Source:0)
	at Qa.w.invokeSuspend(Unknown Source:11)
	at j9.a.resumeWith(Unknown Source:11)
	at Na.f0.run(Unknown Source:130)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7989)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:635)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
	Suppressed: Ta.j: [o1{Cancelling}@3f06432, Dispatchers.Main.immediate]

User actions: 
2024-11-17 15:26:40: MainActivity created
2024-11-17 15:26:42: MainActivity resumed
2024-11-17 15:30:56: MainActivity paused
2024-11-17 15:31:21: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi,<br>This should already be resolved, please reply if not.
