### ISSUE TITLE
Cannot open it

### ISSUE THREAD

**Issue by 1ilir0lika** [maxrave-dev/SimpMusic#570]
**Describe the bug**
I literally cannot open the app

**To Reproduce**
Open it

**Expected behavior**
Should open itself

**Screenshots**
![Screenshot_20241118-202621.png](https://github.com/user-attachments/assets/da464892-8faa-405d-8417-a0a0b8d715f7)

**Log (Error Details)**
Build version: 0.2.4 
Current date: 2024-11-18 20:25:04 
Device: Google Pixel 6a 
OS version: Android 15 (SDK 35) 
 
Stack trace:  
java.lang.IllegalArgumentException: class i6.b isn't parameterized
	at d6.o.checkArgument(SourceFile:4)
	at i6.b.<init>(Unknown Source:15)
	at k7.d.migrate(Unknown Source:38)
	at b4.h0.onUpgrade(Unknown Source:38)
	at g4.k.onUpgrade(Unknown Source:14)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:422)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:323)
	at g4.k.a(Unknown Source:4)
	at g4.k.b(Unknown Source:63)
	at g4.k.getSupportDatabase(Unknown Source:23)
	at g4.m.getWritableDatabase(Unknown Source:9)
	at b4.Y.inTransaction(Unknown Source:4)
	at b4.Y.assertNotSuspendingTransaction(Unknown Source:0)
	at b4.Y.query(Unknown Source:8)
	at d4.b.query(Unknown Source:10)
	at c7.k.call(SourceFile:2)
	at c7.k.call(SourceFile:1)
	at b4.d.invokeSuspend(Unknown Source:86)
	at m9.a.resumeWith(Unknown Source:11)
	at Qa.f0.run(Unknown Source:130)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: Wa.j: [p1{Cancelling}@53bc254, Dispatchers.Main.immediate]

User actions: 
2024-11-18 20:25:01: MainActivity created
2024-11-18 20:25:01: MainActivity resumed

**Comment by CrazyWolf13** [comment]
hi, this should be fixed, please try with version 0.2.19, otherwise report back and I'll reopen this.
