### ISSUE TITLE
Fix bug huawei mate 20 Pro

### ISSUE THREAD

**Issue by marco7722** [maxrave-dev/SimpMusic#584]
Build version: 0.2.4 
Current date: 2024-11-24 20:57:14 
Device: HUAWEI LYA-L29 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.NullPointerException
	at T3.c.onNavDestinationSelected(Unknown Source:28)
	at O5.m.onMenuItemSelected(Unknown Source:142)
	at q.p.a(Unknown Source:4)
	at q.s.invoke(Unknown Source:14)
	at q.p.performItemAction(SourceFile:4)
	at O5.h.onClick(Unknown Source:13)
	at android.view.View.performClick(View.java:7317)
	at android.view.View.performClickInternal(View.java:7291)
	at android.view.View.access$3600(View.java:838)
	at android.view.View$PerformClick.run(View.java:28247)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

User actions: 
2024-11-24 20:55:47: MainActivity created
2024-11-24 20:55:48: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi does this crash still appear with version 0.2.19?

**Comment by 22marco77** [comment]
No. Build 0.2.0

**Comment by CrazyWolf13** [comment]
Alright, then please use the new version, i'll close this issue then.
