### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by GitGitu79** [maxrave-dev/SimpMusic#604]
**Describe the bug**
Crash when opening the app, even though it works fine two hours before. I didn't interact with the app for that two hour so this came out of nowhere.

**To Reproduce**
1. Open app
2. Crash

**Expected behavior**
Open normally

**Screenshots**
![Screenshot_20241207_205152_SimpMusic.png](https://github.com/user-attachments/assets/e26a892a-235e-43e5-b586-182c82a246f1)

**Log (Error Details)**
Build version: 0.2.4 
Current date: 2024-12-07 20:50:06 
Device: Samsung SM-M127F 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.maxrave.simpmusic/com.maxrave.simpmusic.ui.MainActivity}: java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 0
	at java.lang.String.checkBoundsBeginEnd(String.java:4500)
	at java.lang.String.substring(String.java:2527)
	at Oa.G.substring(SourceFile:1)
	at H7.nb.getLocation(Unknown Source:59)
	at com.maxrave.simpmusic.ui.MainActivity.onCreate(Unknown Source:683)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	... 12 more

User actions: 
2024-12-07 20:49:59: MainActivity created

**Comment by maxrave-dev** [comment]
Please change per app language in settings

**Comment by maxrave-dev** [comment]
Thanks, I don't sure about some country code and language code
