### ISSUE TITLE
Time out,check the internet

### ISSUE THREAD

**Issue by abel200734** [maxrave-dev/SimpMusic#618]
I was listening to simpmusic like for almost 1 year up.I didnt have any issues up until now.Whenever i try to play any music,it just keep showing this error saying time out,check the internet.I tried to reinstall and did everything to see any change but none of them work,so please check the issue sir.
![Screenshot_20241213_211132_SimpMusic](https://github.com/user-attachments/assets/bdb8af5d-56c0-41d0-9206-8564a7d55de0)

**Comment by devmikeyy** [comment]
yeah, I've been having that problem too for the past couple hours... maybe it's something with the YouTube Music API

**Comment by ThinethSankalpa** [comment]
Me too

**Comment by abel200734** [comment]
Damn its so annoying @maxrave-dev do something about this bruv

**Comment by maxrave-dev** [comment]
Please log in to your YouTube Account inside Setting in SimpMusic to prevent error
When opening the app, I remind everyone to log in 
![image](https://github.com/user-attachments/assets/a839181b-3ebf-425c-9251-f66a095842dd)
BTW, when I am not logged in, the app still plays music normally
![image](https://github.com/user-attachments/assets/b54af2c2-7a96-47ca-8267-831ba03e68c2)

**Comment by devmikeyy** [comment]
> Please log in to your YouTube Account inside Setting in SimpMusic to prevent error
> When opening the app, I remind everyone to log in 
> ![image](https://github.com/user-attachments/assets/a839181b-3ebf-425c-9251-f66a095842dd)
> BTW, when I am not logged in, the app still plays music normally
> ![image](https://github.com/user-attachments/assets/b54af2c2-7a96-47ca-8267-831ba03e68c2)
> 

i am logged in with YouTube and i still get the same error... a song occasionally starts playing but then the next one won't. ive even reinstalled but no improvement whatsoever.

here is the error log i got once while the error occured:

```
Build version: 0.2.4 
Current date: 2024-12-14 09:02:25 
Device: OPPO CPH1803 
OS version: Android 8.1.0 (SDK 27) 
 
Stack trace:  
java.lang.NullPointerException
	at T3.c.onNavDestinationSelected(Unknown Source:28)
	at O5.m.onMenuItemSelected(Unknown Source:142)
	at q.p.a(Unknown Source:4)
	at q.s.invoke(Unknown Source:14)
	at q.p.performItemAction(SourceFile:4)
	at O5.h.onClick(Unknown Source:13)
	at android.view.View.performClick(View.java:6392)
	at android.view.View$PerformClick.run(View.java:25133)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:198)
	at android.app.ActivityThread.main(ActivityThread.java:7055)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

User actions: 
2024-12-14 09:01:58: MainActivity created
2024-12-14 09:02:00: MainActivity resumed

```

**Comment by abel200734** [comment]
This problem still arrives when im logged into youtube

**Comment by devmikeyy** [comment]
i think the YouTube API for the account has reached rate limit... might reset in 24hrs or so. i say this cause the issue is only with one account I use everyday. Logging in with another Google account works just fine. I'll update on the status tomorrow .

**Comment by ardwiinoo** [comment]
> 
> 
> 
> 
> > i think the YouTube API for the account has reached rate limit... might reset in 24hrs or so. i say this cause the issue is only with one account I use everyday. Logging in with another Google account works just fine. I'll update on the status tomorrow .
> 
> This is not the reason. This problem also occurs when opening a new account.

Yes, when logged out it works just fine

**Comment by maxrave-dev** [comment]
Fixed in nightly build

**Comment by devmikeyy** [comment]
give me the apk find for the nightly version if possible. I can't build the app cos i don't have my pc rn... not that i remember how to do it anyways.

**Comment by devmikeyy** [comment]
i updated the app, cleared data, logged in and out, used proxy and even reinstalled. But still, i have the time out error. Somehow, i can't even play music using guest mode, something I was able to do in V0.2.4![Screenshot_2024-12-23-20-05-42-79.png](https://github.com/user-attachments/assets/a7b44ee7-68cf-41b7-8479-dff436db2d81)

**Comment by CrazyWolf13** [comment]
Duplicate of [https://github.com/maxrave-dev/SimpMusic/issues/1173](https://github.com/maxrave-dev/SimpMusic/issues/1173)

**Comment by karol29sv** [comment]
Any updates?
