### ISSUE TITLE
Playback Error and Application Crash

### ISSUE THREAD

**Issue by daiyut0ng** [maxrave-dev/SimpMusic#621]
Build version: 0.2.4 
Current date: 2024-12-16 22:51:27 
Device: Vivo V2141 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.NullPointerException
	at y7.d1.invokeSuspend(Unknown Source:411)
	at y7.d1.invoke(SourceFile:1)
	at y7.d1.invoke(SourceFile:2)
	at Ta.e0.invokeSuspend(Unknown Source:45)
	at Ta.e0.invoke(SourceFile:1)
	at Ta.e0.invoke(SourceFile:2)
	at Ua.l.invokeSuspend(Unknown Source:38)
	at Ua.l.invoke(SourceFile:1)
	at Ua.l.invoke(SourceFile:2)
	at Xa.b.startCoroutineUndispatched(Unknown Source:31)
	at Qa.U.invoke(Unknown Source:15)
	at Qa.a.start(Unknown Source:0)
	at Qa.i.launch(Unknown Source:22)
	at Qa.g.launch(Unknown Source:0)
	at Qa.i.launch$default(Unknown Source:12)
	at Qa.g.launch$default(Unknown Source:0)
	at Ua.n.emit(Unknown Source:105)
	at Ta.O0.invokeSuspend(Unknown Source:62)
	at Ta.O0.invoke(SourceFile:1)
	at Ta.O0.invoke(SourceFile:2)
	at Ua.w.invokeSuspend(Unknown Source:284)
	at m9.a.resumeWith(Unknown Source:11)
	at Qa.f0.run(Unknown Source:130)
	at Qa.o0.processUnconfinedEvent(Unknown Source:15)
	at Wa.l.resumeCancellableWith(Unknown Source:142)
	at Xa.a.startCoroutineCancellable(SourceFile:1)
	at Xa.a.startCoroutineCancellable$default(Unknown Source:5)
	at Qa.U.invoke(Unknown Source:35)
	at Qa.a.start(Unknown Source:0)
	at Qa.i.launch(Unknown Source:22)
	at Qa.g.launch(Unknown Source:0)
	at Qa.i.launch$default(Unknown Source:12)
	at Qa.g.launch$default(Unknown Source:0)
	at androidx.lifecycle.g0.onStateChanged(Unknown Source:32)
	at androidx.lifecycle.H.dispatchEvent(Unknown Source:24)
	at androidx.lifecycle.I.d(Unknown Source:349)
	at androidx.lifecycle.I.c(Unknown Source:76)
	at androidx.lifecycle.I.handleLifecycleEvent(Unknown Source:14)
	at h2.D0.q(Unknown Source:56)
	at h2.D0.k(Unknown Source:71)
	at h2.t0.z(Unknown Source:1190)
	at h2.t0.M(Unknown Source:91)
	at h2.t0.y(Unknown Source:172)
	at h2.g0.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:1013)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:328)
	at android.app.ActivityThread.main(ActivityThread.java:9224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	Suppressed: Wa.j: [p1{Cancelling}@7b2b25d, Dispatchers.Main.immediate]

User actions: 
2024-12-16 22:51:05: MainActivity created
2024-12-16 22:51:06: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi, can you check if the app does still crash with version 0.2.19?

**Comment by CrazyWolf13** [comment]
Closed, due to no reply and unable to recreate.<br>Please reply if not solved on latest (v0.2.21).
