### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by 7asanka** [maxrave-dev/SimpMusic#631]
**Describe the bug**
The app opens to an error message

**To Reproduce**
1. Open the app

**Expected behavior**
To be met with the home screen

**Screenshots**
![Screenshot_20241220_141600_SimpMusic](https://github.com/user-attachments/assets/dca2a761-f09b-4e1c-9138-c519e5903240)

**Log (Error Details)**
Build version: 0.2.4 
Current date: 2024-12-20 14:14:08 
Device: Samsung SM-G781B 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.IllegalArgumentException: class i6.b isn't parameterized
	at d6.o.checkArgument(SourceFile:4)
	at i6.b.<init>(Unknown Source:15)
	at k7.d.migrate(Unknown Source:38)
	at b4.h0.onUpgrade(Unknown Source:38)
	at g4.k.onUpgrade(Unknown Source:14)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:515)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:413)
	at g4.k.a(Unknown Source:4)
	at g4.k.b(Unknown Source:63)
	at g4.k.getSupportDatabase(Unknown Source:23)
	at g4.m.getWritableDatabase(Unknown Source:9)
	at b4.Y.inTransaction(Unknown Source:4)
	at b4.Y.assertNotSuspendingTransaction(Unknown Source:0)
	at b4.Y.query(Unknown Source:8)
	at d4.b.query(Unknown Source:10)
	at c7.k.call(SourceFile:2)
	at c7.k.call(SourceFile:1)
	at b4.d.invokeSuspend(Unknown Source:86)
	at m9.a.resumeWith(Unknown Source:11)
	at Qa.f0.run(Unknown Source:130)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: Wa.j: [p1{Cancelling}@673b791, Dispatchers.Main.immediate]

User actions: 
2024-12-20 14:13:50: MainActivity created
2024-12-20 14:13:51: MainActivity resumed

**Comment by 7asanka** [comment]
I managed to start by clearing app data, however when I restore data, the app breaks again.
