### ISSUE TITLE
NPE time

### ISSUE THREAD

**Issue by Zdertis420** [maxrave-dev/SimpMusic#641]
When I opened my playlist, the cover image and download button were glitching. Then I pressed download and the app crashed with null pointer exception.

P.S. I can't reproduce this bug

Glitches: https://github.com/user-attachments/assets/a0474db6-70f5-46d5-a04b-8c269c255895

Trace:
Build version: 0.2.5 
Current date: 2024-12-23 00:40:16 
Device: Samsung SM-S928B 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.NullPointerException
	at A7.q0.onClick(Unknown Source:179)
	at android.view.View.performClick(View.java:8055)
	at android.view.View.performClickInternal(View.java:8032)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31923)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

User actions: 
2024-12-23 00:37:54: MainActivity created
2024-12-23 00:37:55: MainActivity resumed
2024-12-23 00:38:21: MainActivity paused
2024-12-23 00:38:44: MainActivity resumed
2024-12-23 00:39:04: MainActivity paused
2024-12-23 00:39:42: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi, can you reproduce this on 0.2.19?
