### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Zdertis420** [maxrave-dev/SimpMusic#647]
When I logged in, the app crashed with error

Build version: 0.2.5 
Current date: 2024-12-24 12:02:34 
Device: Samsung SM-S928B 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IllegalStateException: Fragment LogInFragment{37168b2} (3638ffe8-5691-42b1-acb6-b675f010dc86) not attached to a context.
	at h2.H.requireContext(Unknown Source:17)
	at z7.b.onPageFinished(Unknown Source:86)
	at WV.WY.b(chromium-TrichromeWebViewGoogle6432.aab-stable-677813533:12)
	at WV.g7.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-677813533:261)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

User actions: 
2024-12-24 12:01:49: MainActivity created
2024-12-24 12:01:49: MainActivity resumed
2024-12-24 12:01:50: MainActivity paused
2024-12-24 12:01:50: MainActivity destroyed
2024-12-24 12:01:50: MainActivity created
2024-12-24 12:01:50: MainActivity resumed
2024-12-24 12:01:50: MainActivity paused
2024-12-24 12:01:52: MainActivity resumed
2024-12-24 12:02:14: MainActivity paused
2024-12-24 12:02:17: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Can you replicate this with 0.2.20?
