### ISSUE TITLE
Random npe

### ISSUE THREAD

**Issue by Zdertis420** [maxrave-dev/SimpMusic#658]
Build version: 0.2.7 
Current date: 2024-12-26 01:46:18 
Device: Samsung SM-S928B 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.NullPointerException
	at A7.q0.onClick(Unknown Source:179)
	at android.view.View.performClick(View.java:8055)
	at android.view.View.performClickInternal(View.java:8032)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31923)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

User actions: 
2024-12-26 01:40:11: MainActivity created
2024-12-26 01:40:12: MainActivity resumed
2024-12-26 01:40:31: MainActivity paused
2024-12-26 01:40:37: MainActivity resumed
2024-12-26 01:40:53: MainActivity paused
2024-12-26 01:40:56: MainActivity resumed
2024-12-26 01:43:07: MainActivity paused
2024-12-26 01:43:12: MainActivity resumed
2024-12-26 01:44:44: MainActivity paused
2024-12-26 01:44:46: MainActivity resumed
2024-12-26 01:44:50: MainActivity paused
2024-12-26 01:44:50: LibsActivity created
2024-12-26 01:44:50: LibsActivity resumed
2024-12-26 01:45:07: LibsActivity paused
2024-12-26 01:45:11: LibsActivity resumed
2024-12-26 01:45:29: LibsActivity paused
2024-12-26 01:45:31: LibsActivity resumed
2024-12-26 01:45:32: LibsActivity paused
2024-12-26 01:45:32: MainActivity resumed
2024-12-26 01:45:32: LibsActivity destroyed

**Comment by CrazyWolf13** [comment]
Hi, is this still an issue as of version 0.2.19?
