### ISSUE TITLE
The app is not usable, even after logging in

### ISSUE THREAD

**Issue by pedr0m9** [maxrave-dev/SimpMusic#662]
After logging in, you click any song and this is the error you'll receive

Build version: 0.2.7 
Current date: 2024-12-26 03:26:02 
Device: Motorola XT2125-4 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.RuntimeException: Cannot initialize effect engine for type: fe3199be-aed0-413f-87bb-11260eb63cf1 Error: -3
	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:543)
	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:501)
	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:475)
	at android.media.audiofx.LoudnessEnhancer.<init>(LoudnessEnhancer.java:80)
	at p7.O0.onMediaItemTransition(Unknown Source:78)
	at B2.z.invoke(Unknown Source:13)
	at u2.w.invoke(Unknown Source:17)
	at B2.u0.run(Unknown Source:31)
	at u2.x.flushEvents(Unknown Source:63)
	at B2.Q.z(Unknown Source:874)
	at B2.Q.t(Unknown Source:196)
	at B2.Q.setMediaSources(SourceFile:2)
	at B2.Q.setMediaItems(SourceFile:2)
	at r2.k.setMediaItems(Unknown Source:4)
	at r2.k.setMediaItem(SourceFile:1)
	at p7.O0.addMediaItem(Unknown Source:16)
	at L7.d.invokeSuspend(Unknown Source:28)
	at h9.a.resumeWith(Unknown Source:11)
	at Ma.c0.run(Unknown Source:125)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8601)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
	Suppressed: Sa.g: [g1{Cancelling}@4875d05, Dispatchers.Main.immediate]

User actions: 
2024-12-26 03:25:50: MainActivity created
2024-12-26 03:25:51: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi, this has been fixed, try again with version 0.2.19.<br>Pleas reply if not fixed.

**Comment by CrazyWolf13** [comment]
Closed, due to no reply and unable to recreate.<br>Please reply if not solved on latest (v0.2.21).
