### ISSUE TITLE
Big Bug

### ISSUE THREAD

**Issue by daksh396** [maxrave-dev/SimpMusic#663]
Build version: 0.2.7 
Current date: 2024-12-26 22:56:36 
Device: Xiaomi 23124RN87I 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IllegalArgumentException: Key "A_TlayzlfvU" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at M0.a0.subcompose(Unknown Source:153)
	at M0.S.subcompose(Unknown Source:2)
	at I.w0.measure-0kLqBqw(Unknown Source:33)
	at G.K.getAndMeasure-0kLqBqw(Unknown Source:19)
	at G.K.getAndMeasure-0kLqBqw$default(Unknown Source:8)
	at G.H.measureLazyList-x0Ok8Vo(Unknown Source:352)
	at G.C.invoke-0kLqBqw(Unknown Source:486)
	at G.C.invoke(Unknown Source:8)
	at I.q0.invoke-0kLqBqw(Unknown Source:13)
	at I.q0.invoke(Unknown Source:8)
	at M0.V.measure-3p2s80s(Unknown Source:92)
	at O0.N.measure-BRTryo0(Unknown Source:72)
	at w0.b1.measure-3p2s80s(Unknown Source:0)
	at O0.a0.measure-BRTryo0(Unknown Source:40)
	at F.X.measure-3p2s80s(Unknown Source:98)
	at O0.a0.measure-BRTryo0(Unknown Source:40)
	at O0.F0.invoke(SourceFile:2)
	at O0.F0.invoke(SourceFile:1)
	at n0.o.observe(Unknown Source:128)
	at n0.M.observe(Unknown Source:54)
	at n0.Q.observeReads(Unknown Source:133)
	at O0.W1.observeReads$ui_release(Unknown Source:2)
	at O0.W1.observeMeasureSnapshotReads$ui_release(Unknown Source:16)
	at O0.G0.access$performMeasure-BRTryo0(Unknown Source:35)
	at O0.D0.remeasure-BRTryo0(Unknown Source:127)
	at O0.n0.remeasure-_Sx5XlM$ui_release(Unknown Source:19)
	at O0.S0.c(Unknown Source:4)
	at O0.S0.measureAndLayout-0kLqBqw(Unknown Source:107)
	at P0.b0.measureAndLayout-0kLqBqw(Unknown Source:7)
	at O0.n0.forceRemeasure(Unknown Source:41)
	at G.e0.onScroll$foundation_release(Unknown Source:114)
	at G.b0.invoke(SourceFile:1)
	at G.b0.invoke(SourceFile:2)
	at C.v.scrollBy(Unknown Source:18)
	at C.v1.access$performScroll-3eAAhYA(Unknown Source:22)
	at C.t1.invoke-MK-Hz9U(Unknown Source:10)
	at C.t1.invoke(Unknown Source:6)
	at A.r.applyToScroll-Rhakbz0(Unknown Source:240)
	at C.r1.scrollByWithOverscroll-OzD1aCk(Unknown Source:25)
	at C.p1.scrollBy(Unknown Source:20)
	at C.q.invoke(SourceFile:3)
	at C.q.invoke(SourceFile:1)
	at z.U0.a(Unknown Source:56)
	at z.U0.access$doAnimationFrameWithScale(Unknown Source:0)
	at z.Q0.invoke(SourceFile:2)
	at z.Q0.invoke(SourceFile:1)
	at z.T0.invoke(SourceFile:2)
	at z.T0.invoke(SourceFile:1)
	at d0.i.resume(Unknown Source:8)
	at d0.k.sendFrame(Unknown Source:29)
	at d0.M1.invoke(SourceFile:5)
	at d0.M1.invoke(SourceFile:1)
	at P0.u1.doFrame(Unknown Source:8)
	at P0.q1.access$performFrameDispatch(Unknown Source:33)
	at P0.p1.doFrame(Unknown Source:12)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1713)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1724)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1220)
	at android.view.Choreographer.doFrame(Choreographer.java:1077)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1688)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8742)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1090)
	Suppressed: Sa.g: [P0.J2@31ff850, d0.k@254a49, g1{Cancelling}@9f90f4e, q1@609786f]

User actions: 
2024-12-26 22:54:09: MainActivity created
2024-12-26 22:54:10: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi, can you recreate this in version 0.2.20?
