### ISSUE TITLE
Error after restore from backup

### ISSUE THREAD

**Issue by starvirus10** [maxrave-dev/SimpMusic#670]
Log file : 
Build version: 0.2.7 
Current date: 2024-12-29 09:56:56 
Device: Xiaomi M2102J20SG 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.StringIndexOutOfBoundsException: length=0; index=2
	at java.lang.String.substring(String.java:2060)
	at Ka.G.substring(SourceFile:1)
	at j7.t0.invokeSuspend(Unknown Source:37)
	at j7.t0.invoke(SourceFile:1)
	at j7.t0.invoke(SourceFile:2)
	at Pa.a0.invokeSuspend(Unknown Source:45)
	at Pa.a0.invoke(SourceFile:1)
	at Pa.a0.invoke(SourceFile:2)
	at Qa.l.invokeSuspend(Unknown Source:38)
	at Qa.l.invoke(SourceFile:1)
	at Qa.l.invoke(SourceFile:2)
	at Ta.b.startCoroutineUndispatched(Unknown Source:34)
	at Ma.Q.invoke(Unknown Source:15)
	at Ma.a.start(Unknown Source:0)
	at Ma.i.launch(Unknown Source:22)
	at Ma.g.launch(Unknown Source:0)
	at Ma.i.launch$default(Unknown Source:12)
	at Ma.g.launch$default(Unknown Source:0)
	at Qa.n.emit(Unknown Source:105)
	at Pa.K0.invokeSuspend(Unknown Source:62)
	at Pa.K0.invoke(SourceFile:1)
	at Pa.K0.invoke(SourceFile:2)
	at Qa.w.invokeSuspend(Unknown Source:284)
	at h9.a.resumeWith(Unknown Source:11)
	at Ma.c0.run(Unknown Source:125)
	at Ma.l0.processUnconfinedEvent(Unknown Source:15)
	at Ma.d0.dispatch(Unknown Source:73)
	at Ma.p.b(Unknown Source:13)
	at Ma.p.completeResume(Unknown Source:2)
	at Oa.m.access$tryResume0(Unknown Source:7)
	at Oa.f.tryResumeHasNext(Unknown Source:22)
	at Oa.k.n(Unknown Source:49)
	at Oa.k.access$updateCellSend(Unknown Source:56)
	at Oa.k.send(Unknown Source:92)
	at Oa.p.send(Unknown Source:2)
	at W1.w.emit(Unknown Source:4)
	at Qa.I.invoke(SourceFile:1)
	at Qa.I.invoke(SourceFile:2)
	at Qa.H.a(Unknown Source:84)
	at Qa.H.emit(Unknown Source:0)
	at W1.H.invokeSuspend(Unknown Source:97)
	at h9.a.resumeWith(Unknown Source:11)
	at Ma.c0.run(Unknown Source:125)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:77)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:306)
	Suppressed: Sa.g: [g1{Cancelling}@4fd2ea2, Dispatchers.Main.immediate]

User actions: 
2024-12-29 09:56:42: MainActivity created
2024-12-29 09:56:43: MainActivity resumed

**Comment by CrazyWolf13** [comment]
Hi,<br>Please check if this issue still appears with version 0.2.19.

**Comment by CrazyWolf13** [comment]
Closed, due to no reply and unable to recreate.<br>Please reply if not solved on latest (v0.2.21).
