### ISSUE TITLE
Lỗi không có kết nối mạng và không thể đăng nhập YouTube 

### ISSUE THREAD

**Issue by Satnhanas** [maxrave-dev/SimpMusic#675]
Build version: 0.2.7 
Current date: 2024-12-31 20:00:13 
Device: Realme RMX3630 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IllegalStateException: Fragment LogInFragment{951afee} (60fd7b38-999a-4e22-a941-c46402c235dd) not attached to a context.
	at h2.H.requireContext(Unknown Source:17)
	at z7.c.onPageFinished(Unknown Source:86)
	at WV.WY.b(chromium-TrichromeWebViewGoogle6432.aab-stable-677813533:12)
	at WV.g7.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-677813533:261)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

User actions: 
2024-12-31 19:58:32: MainActivity created
2024-12-31 19:58:32: MainActivity resumed
2024-12-31 19:59:03: MainActivity paused
2024-12-31 19:59:03: MainActivity resumed
2024-12-31 19:59:04: MainActivity paused
2024-12-31 19:59:05: MainActivity resumed
2024-12-31 19:59:05: MainActivity paused
2024-12-31 19:59:05: MainActivity resumed
2024-12-31 19:59:10: MainActivity paused
2024-12-31 19:59:10: MainActivity resumed
2024-12-31 19:59:10: MainActivity paused
2024-12-31 19:59:11: MainActivity resumed
2024-12-31 19:59:11: MainActivity paused
2024-12-31 19:59:11: MainActivity resumed
2024-12-31 19:59:17: MainActivity paused
2024-12-31 19:59:17: MainActivity resumed
2024-12-31 19:59:17: MainActivity paused
2024-12-31 19:59:17: MainActivity resumed
2024-12-31 19:59:18: MainActivity paused
2024-12-31 19:59:18: MainActivity resumed
![Screenshot_2024-12-31-20-06-43-71_b4450e33c7076f102e79bbedaff38911](https://github.com/user-attachments/assets/18b9395b-c10a-4975-bd86-d4da9ad2dbcf)
![Screenshot_2024-12-31-20-06-43-71_b4450e33c7076f102e79bbedaff38911](https://github.com/user-attachments/assets/c643c973-1a90-46bb-975e-e4b2a1f68acb)

**Comment by CrazyWolf13** [comment]
Hi, can you check with latest version 0.2.19?

**Comment by CrazyWolf13** [comment]
Closed, due to no reply and unable to recreate.<br>Please reply if not solved on latest (v0.2.21).
