### ISSUE TITLE
Crash on starting 

### ISSUE THREAD

**Issue by Justavinash09** [maxrave-dev/SimpMusic#82]
Build version: 0.1.3-beta 
Current date: 2023-09-10 16:16:31 
Device: Xiaomi 23049PCD8I 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.IllegalStateException: A migration from 1 to 3 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.kt:110)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.kt:253)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:232)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:190)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.kt:638)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.kt:457)
	at androidx.room.RoomDatabase.query(RoomDatabase.kt:486)
	at androidx.room.util.DBUtil.query(DBUtil.kt:75)
	at com.maxrave.simpmusic.data.db.DatabaseDao_Impl$67.call(DatabaseDao_Impl.java:2516)
	at com.maxrave.simpmusic.data.db.DatabaseDao_Impl$67.call(DatabaseDao_Impl.java:2513)
	at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:88)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@26d0e56, Dispatchers.Main.immediate]

User actions: 
2023-09-10 16:16:18: MainActivity created
2023-09-10 16:16:19: MainActivity resumed
2023-09-10 16:16:19: MainActivity paused

**Comment by maxrave-dev** [comment]
Not support updated from too old version. Remove data or update to 0.1.2 version before then update to latest version

**Comment by licaon-kter** [comment]
If they're already on 0.1.3 they can't downgrade to 0.1.2, fyi, _Android Security Feature_
