### ISSUE TITLE
Crash after logging in 

### ISSUE THREAD

**Issue by The-Ducktor** [maxrave-dev/SimpMusic#91]
When I try to use the google login it works but then if I refresh the main page it crashes and if I logout it no longer crashes/ unexpected error![Screenshot_20230913-152053.png](https://github.com/maxrave-dev/SimpMusic/assets/130664593/a536df47-c018-4fab-b93f-0cae221c6f9c)

```
Build version: 0.1.3-beta 
Current date: 2023-09-13 15:22:27 
Device: Google Pixel 4 XL 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:418)
	at com.maxrave.simpmusic.adapter.home.chart.TrackChartAdapter.onBindViewHolder(TrackChartAdapter.kt:51)
	at com.maxrave.simpmusic.adapter.home.chart.TrackChartAdapter.onBindViewHolder(TrackChartAdapter.kt:12)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7678)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7761)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6582)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6848)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3981)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1240)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26496)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1921)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:640)
	at android.view.View.measure(View.java:26496)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26496)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:704)
	at android.view.View.measure(View.java:26496)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26496)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:760)
	at android.view.View.measure(View.java:26496)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4038)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2654)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2960)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2367)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9293)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

User actions: 
2023-09-13 15:22:22: MainActivity created
2023-09-13 15:22:23: MainActivity resumed

```

**Comment by The-Ducktor** [comment]
tied with a vpn no difference also tried clearing all the app data same problem

**Comment by maxrave-dev** [comment]
Can you see chart in music.youtube.com with your using account?

**Comment by The-Ducktor** [comment]
perhaps not i'm not sure what you mean?

**Comment by maxrave-dev** [comment]
> perhaps not i'm not sure what you mean

I mean what step you do in SimpMusic before crashing

**Comment by The-Ducktor** [comment]
the app works normally play search etc but then if i login and refresh. the homescreen it crashes

**Comment by maxrave-dev** [comment]
> perhaps not i'm not sure what you mean?

Sorry for the wrong reply, I mean when you go to music.youtube.com with the problem account, did you see Charts ?

**Comment by The-Ducktor** [comment]
I don't see a chart (like a graph?) on the one that worked or the one that didn't 

[My lovly yt music homescreen for the crashing one](https://github.com/maxrave-dev/SimpMusic/assets/130664593/a579216d-41de-48ec-93cc-db5c06a71d4d)

**Comment by The-Ducktor** [comment]
thanks for the direction
there is stuff thier
[The Stuff](https://github.com/maxrave-dev/SimpMusic/assets/130664593/f6b54836-a3c6-49ad-9c79-839c2d61c6d2)

**Comment by maxrave-dev** [comment]
hmm, I don't know why if you can supply me with this account for testing, it will be great!

**Comment by The-Ducktor** [comment]
I'm sorry but i'm unwilling provide my accounts for security and personal reasons but would be happy to give other kinds of info that you might find useful.

**Comment by maxrave-dev** [comment]
Fixed in next build
