### ISSUE TITLE
APP crashes

### ISSUE THREAD

**Issue by siggi1984** [maxrave-dev/SimpMusic#93]
Build version: 0.1.3-beta 
Current date: 2023-09-13 18:34:57 
Device: Samsung SM-A217F 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.IllegalArgumentException: Navigation action/destination com.maxrave.simpmusic:id/action_bottom_navigation_item_library_to_favoriteFragment cannot be found from the current destination Destination(com.maxrave.simpmusic:id/favoriteFragment) label=fragment_favorite class=com.maxrave.simpmusic.ui.fragment.library.FavoriteFragment
	at androidx.navigation.NavController.navigate(NavController.kt:1674)
	at androidx.navigation.NavController.navigate(NavController.kt:1603)
	at androidx.navigation.NavController.navigate(NavController.kt:1585)
	at androidx.navigation.NavController.navigate(NavController.kt:1568)
	at com.maxrave.simpmusic.ui.fragment.library.LibraryFragment.onViewCreated$lambda$4(LibraryFragment.kt:397)
	at com.maxrave.simpmusic.ui.fragment.library.LibraryFragment.$r8$lambda$-QZ_pQYkzLmToMVMfKgkZyXdDOM(Unknown Source:0)
	at com.maxrave.simpmusic.ui.fragment.library.LibraryFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7792)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

User actions: 
2023-09-13 18:16:33: MainActivity created
2023-09-13 18:16:34: MainActivity resumed
2023-09-13 18:16:34: MainActivity paused
2023-09-13 18:16:34: MainActivity destroyed
2023-09-13 18:16:34: MainActivity created
2023-09-13 18:16:35: MainActivity resumed
2023-09-13 18:17:10: MainActivity paused
2023-09-13 18:17:20: MainActivity resumed
2023-09-13 18:19:11: MainActivity paused
2023-09-13 18:19:23: MainActivity resumed
2023-09-13 18:21:10: MainActivity paused
2023-09-13 18:21:17: MainActivity resumed
2023-09-13 18:21:38: MainActivity paused
2023-09-13 18:31:27: MainActivity resumed
2023-09-13 18:31:29: MainActivity paused
2023-09-13 18:32:16: MainActivity resumed
2023-09-13 18:32:21: MainActivity paused
2023-09-13 18:32:34: MainActivity resumed
2023-09-13 18:33:42: MainActivity paused
2023-09-13 18:33:46: MainActivity resumed
2023-09-13 18:34:07: MainActivity paused
2023-09-13 18:34:18: MainActivity resumed

**Comment by maxrave-dev** [comment]
Did this bug appear more than 2 times?

**Comment by siggi1984** [comment]
oh yes several times

**Comment by maxrave-dev** [comment]
Can you describe to me step by step caused this bug

**Comment by siggi1984** [comment]
So when the APP plays music, everything is fine at first, but when I change the tab, for example. If you go to search or go to the library or link a song, the app sometimes crashes.

**Comment by maxrave-dev** [comment]
@siggi1984 may be crashing caused memory low. I don't why, I will test in some low memory device

**Comment by kztera** [comment]
> @siggi1984 may be crashing caused memory low. I don't why, I will test in some low memory device

Máy mình 8gb mà vẫn crash liên tọi này.  Cứ chạy được tí thì lại tự thoát


Build version: 0.1.3-beta 
Current date: 2023-09-25 12:37:30 
Device: Xiaomi M2012K11AG 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 21, Size: 14
	at java.util.ArrayList.add(ArrayList.java:483)
	at com.maxrave.simpmusic.service.test.source.FetchQueue$onStartCommand$1$1.emit(FetchQueue.kt:61)
	at com.maxrave.simpmusic.service.test.source.FetchQueue$onStartCommand$1$1.emit(FetchQueue.kt:47)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:396)
	at kotlinx.coroutines.flow.ReadonlyStateFlow.collect(Unknown Source:2)
	at com.maxrave.simpmusic.service.test.source.FetchQueue$onStartCommand$1.invokeSuspend(FetchQueue.kt:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b062269, Dispatchers.Main]

User actions: 
2023-09-25 12:34:46: MainActivity created
2023-09-25 12:34:47: MainActivity resumed
2023-09-25 12:36:52: MainActivity paused
2023-09-25 12:37:08: MainActivity resumed
